#!/usr/bin/env python3
"""
SB-007 REQUEST_ID LINEAGE — RUNTIME VERIFICATION
HG DIRECTIVE: Execute existing dispatch_multi_request() and verify request_id lineage

Constraints:
- Use EXISTING dispatch_multi_request() code only
- Use REAL request_id generated by the runtime
- Verify request_id reaches Event Store via _record_lineage_events()
- NO code changes
- NO new implementations
- NO request_id fabrication
"""

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import sqlite3
from datetime import datetime, timezone

# Step 1: Execute existing dispatch_multi_request()
print("\n" + "="*80)
print("STEP 1: EXECUTE EXISTING dispatch_multi_request()")
print("="*80)

try:
    from gateway.multi_dispatcher import dispatch_multi_request

    # Use minimal request with existing providers
    request_text = "SB-007 REQUEST_ID LINEAGE VERIFICATION TEST"
    providers = ["gpt", "claude"]  # Use existing configured providers

    print(f"\nExecuting dispatch_multi_request()...")
    print(f"  request_text: {request_text}")
    print(f"  providers: {providers}")

    response = dispatch_multi_request(
        request_text=request_text,
        providers=providers,
        title="SB-007 Request-ID Lineage Test"
    )

    print(f"\nResponse received from dispatch_multi_request():")
    print(f"  status: {response.get('status')}")
    print(f"  request_id: {response.get('request_id')}")

    runtime_request_id = response.get('request_id')

    if not runtime_request_id:
        print("\n✗ FAIL: request_id not returned from dispatch_multi_request()")
        sys.exit(1)

    print(f"\n✓ RUNTIME REQUEST_ID CAPTURED: {runtime_request_id}")

except Exception as e:
    print(f"\n✗ EXCEPTION during dispatch_multi_request(): {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Step 2: Query Event Store for lineage events with this request_id
print("\n" + "="*80)
print("STEP 2: QUERY EVENT STORE FOR LINEAGE EVENTS")
print("="*80)

db_path = str(_REPO_ROOT / 'data' / 'mocka_events.db')
conn = sqlite3.connect(db_path)
conn.row_factory = sqlite3.Row

try:
    # Search for audit events with this request_id from orchestra
    cursor = conn.execute('''
        SELECT event_id, request_id, what_type, where_component, vendor, model,
               runtime, source, session_id, how_trigger, where_path, trace_id as after_hash
        FROM events
        WHERE request_id = ?
        ORDER BY event_id DESC
        LIMIT 10
    ''', (runtime_request_id,))

    lineage_events = cursor.fetchall()

    print(f"\nSearching for events with request_id = {runtime_request_id}")
    print(f"Results found: {len(lineage_events)}")

    if len(lineage_events) == 0:
        print("\n✗ FAIL: No events found with this request_id in Event Store")
        sys.exit(1)

    print("\nLineage events found:")
    for event in lineage_events:
        event_dict = dict(event)
        print(f"\n  event_id: {event_dict.get('event_id')}")
        print(f"  request_id: {event_dict.get('request_id')}")
        print(f"  what_type: {event_dict.get('what_type')}")
        print(f"  where_component: {event_dict.get('where_component')}")
        print(f"  vendor: {event_dict.get('vendor')}")
        print(f"  model: {event_dict.get('model')}")
        print(f"  runtime: {event_dict.get('runtime')}")
        print(f"  source: {event_dict.get('source')}")
        print(f"  session_id: {event_dict.get('session_id')}")
        print(f"  how_trigger: {event_dict.get('how_trigger')}")
        print(f"  where_path: {event_dict.get('where_path')}")
        print(f"  after_hash: {event_dict.get('after_hash')}")

    # Verify request_id consistency
    print("\n" + "="*80)
    print("STEP 3: VERIFY REQUEST_ID LINEAGE PRESERVATION")
    print("="*80)

    all_match = True
    for event in lineage_events:
        event_dict = dict(event)
        stored_request_id = event_dict.get('request_id')

        if stored_request_id != runtime_request_id:
            print(f"\n✗ MISMATCH: Runtime={runtime_request_id}, Stored={stored_request_id}")
            all_match = False

    if not all_match:
        print("\n✗ FAIL: request_id mismatch in Event Store")
        sys.exit(1)

    print(f"\n✓ ALL EVENTS MATCH: request_id = {runtime_request_id}")

finally:
    conn.close()

# Step 4: Assess #05 and #18
print("\n" + "="*80)
print("STEP 4: ASSESS #05 AND #18")
print("="*80)

point_05_pass = len(lineage_events) > 0 and runtime_request_id is not None
point_18_pass = all_match and runtime_request_id is not None

print(f"\n#05 request_id:")
print(f"  Runtime generated: {runtime_request_id}")
print(f"  Event Store stored: {'YES' if len(lineage_events) > 0 else 'NO'}")
print(f"  Result: {'✓ PASS' if point_05_pass else '✗ FAIL'}")

print(f"\n#18 request_id_lineage_preservation:")
print(f"  Runtime → Event Store: {'✓ VERIFIED' if all_match else '✗ NOT VERIFIED'}")
print(f"  Result: {'✓ PASS' if point_18_pass else '✗ FAIL'}")

# Step 5: Final assessment
print("\n" + "="*80)
print("FINAL ASSESSMENT")
print("="*80)

new_18_point_count = 16 + (1 if point_05_pass else 0) + (1 if point_18_pass else 0)

print(f"\nPrevious 18-Point: 16/18")
print(f"New points: #05={'PASS' if point_05_pass else 'FAIL'}, #18={'PASS' if point_18_pass else 'FAIL'}")
print(f"New 18-Point: {new_18_point_count}/18")

if new_18_point_count == 18:
    print(f"\n✓ COMMIT GATE: SATISFIED")
else:
    print(f"\n✗ COMMIT GATE: UNSATISFIED")

print(f"\nRUNTIME REQUEST_ID: {runtime_request_id}")
print(f"SAMPLE LINEAGE EVENT: {lineage_events[0]['event_id'] if lineage_events else 'N/A'}")

print("\n" + "="*80)
print(f"18-POINT RESULT: {new_18_point_count}/18")
print("="*80)

sys.exit(0 if new_18_point_count == 18 else 1)
