#!/usr/bin/env python3
"""
TRACE REQUEST_ID FLOW
Analyze the code path to understand why request_id is NULL
"""

print("=== REQUEST_ID FLOW ANALYSIS ===")
print()

print("STEP 1: Request Entry Point")
print("-" * 70)
print("/mcp endpoint (line 1265-1290)")
print("  Line 1271: req_id = body.get('id')")
print("             ✓ Extracts JSON-RPC 'id' field")
print()
print("  Line 1283: execute_tool(..., req_id=req_id)")
print("             ✓ Passes req_id to execute_tool()")
print()

print("STEP 2: execute_tool() function")
print("-" * 70)
print("Function signature (line 595):")
print("  def execute_tool(name, args, req_id=None)")
print("             ✓ req_id parameter defined")
print()
print("Logic flow:")
print("  Line 621: before_tool(name, args, req_id=req_id, session_id=SESSION_ID)")
print("           ✓ req_id passed to before_tool()")
print()
print("  Line 626-631:")
print("    _record_governance_block(")
print("        req_id=str(req_id) if req_id else 'N/A',")
print("        ...")
print("    )")
print("           ✓ req_id converted and passed to _record_governance_block()")
print()

print("STEP 3: _record_governance_block() function")
print("-" * 70)
print("Function signature (line 283):")
print("  def _record_governance_block(req_id: str, ...)")
print("             ✓ req_id parameter received")
print()
print("Payload assembly (line 295-309):")
print("  gate_payload = {")
print("      ...")
print("      'request_id': req_id,  ← line 308")
print("  }")
print("             ✓ request_id added to payload")
print()
print("Execution paths:")
print("  A. Online (line 312): requests.post(GATE_URL, json=gate_payload)")
print("     → phi_os/event_gate.process_event via HTTP")
print()
print("  B. Offline (line 324): _gate_process_event(gate_payload, event_source='live')")
print("     → phi_os.event_gate.process_event direct call")
print()

print("STEP 4: phi_os/event_gate.py processing")
print("-" * 70)
print("Function: process_event()")
print("  (NOT DIRECTLY SHOWN IN READ - need to trace)")
print()
print("Function: _write() (line 46)")
print("  Payload mapping (line 51-76):")
print("    row = {")
print("      ...")
print("      'request_id': payload.get('request_id'),  ← line 75")
print("    }")
print("           ✓ Extracts request_id from payload")
print()
print("  Empty string handling (line 78):")
print("    row = {k: (v if v != '' else None) for k, v in row.items()}")
print("           ✓ Converts empty strings to None")
print()
print("  Database insert (line 86-89):")
print("    INSERT OR IGNORE INTO events (...) VALUES (...)")
print("           ✓ Inserts row (including request_id)")
print()

print("=" * 70)
print("PROBLEM DIAGNOSIS")
print("=" * 70)
print()

print("THEORY 1: req_id is None at entry point")
print("-" * 70)
print("If /mcp request's 'id' field is missing:")
print("  body.get('id') → None")
print("  str(None) if None else 'N/A' → 'N/A'")
print("  gate_payload['request_id'] = 'N/A'")
print()
print("Then in event_gate.py _write():")
print("  'N/A' != '' → 'N/A' (stored as 'N/A', not NULL)")
print()
print("But actual result is NULL, so req_id must be None/empty")
print()

print("THEORY 2: req_id is empty string at entry point")
print("-" * 70)
print("If body.get('id') returns empty string '':")
print("  str('') if '' else 'N/A' → 'N/A'")
print("  gate_payload['request_id'] = 'N/A'")
print()
print("Result: NULL in DB (same as above)")
print()

print("THEORY 3: event_gate.process_event() loses request_id")
print("-" * 70)
print("If process_event() has different entry point than _write():")
print("  payload assembly might be different")
print("  Check: Is there a wrapper that modifies the payload?")
print()

print("=" * 70)
print("VERIFICATION NEEDED")
print("=" * 70)
print()
print("To determine actual cause:")
print()
print("1. Add debug logging to execute_tool() to print req_id value")
print("2. Add debug logging to _record_governance_block() to print payload")
print("3. Check phi_os/event_gate.py for process_event() implementation")
print("4. Verify event_source parameter handling")
print()

print("=" * 70)
print("CURRENT CODE PATH VERDICT")
print("=" * 70)
print()
print("Code assembly is CORRECT (A+B implemented properly)")
print("  ✓ /mcp extracts req_id from JSON-RPC 'id'")
print("  ✓ execute_tool receives req_id parameter")
print("  ✓ before_tool receives req_id parameter")
print("  ✓ _record_governance_block receives req_id parameter")
print("  ✓ gate_payload['request_id'] is assembled")
print()
print("Persistence issue is downstream:")
print("  ? phi_os/event_gate.py process_event() or _write()")
print()
print("SCOPE B STATUS: PARTIAL")
print("  - Transmission: WORKING (code path verified)")
print("  - Persistence: ISSUE (request_id=NULL in database)")
print()
