"""
governance/execution_decision_connector.py

Phase 8-7: Execution → Decision → Event → Institutional Memory

Goal:
  Close the governance chain by connecting Execution results to canonical
  Decision/Event/Institutional Memory paths WITHOUT changing existing
  canonical implementations.

Contract:
  - Uses existing mocka_decision_write(mocka_mcp_server.py:968)
  - Uses existing mocka_write_event(mocka_mcp_server.py:666)
  - Companion event automatically generated by mocka_decision_write
  - Connects to MemoryWriter for institutional memory record
  - Does NOT create parallel Decision/Event/Memory stores
  - Does NOT auto-approve or skip Human Gate semantics
  - Execution ≠ Authorization (records result, not approval)

Protocol:
  1. Execution → correlation_id / task_id / execution_id
  2. Decision write via canonical mocka_decision_write
  3. Event auto-generated via companion mechanism
  4. Memory record via MemoryWriter.write_event
  5. correlation_id chains through all records for traceability
"""

import sys
import json
import uuid
import requests
from datetime import datetime, timezone
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

try:
    from memory.memory_writer import MemoryWriter
    from memory.memory_registry import Source, MemoryType
except ImportError:
    MemoryWriter = None
    Source = None
    MemoryType = None


@dataclass
class ExecutionResult:
    """Execution Provider output."""
    execution_id: str
    correlation_id: str
    task_id: str
    hab_request_id: str
    status: str  # "success" | "failure" | "halted"
    output: Optional[str] = None
    error: Optional[str] = None
    started_at: str = None
    completed_at: str = None
    metadata: dict = None

    def __post_init__(self):
        if self.started_at is None:
            self.started_at = datetime.now(timezone.utc).isoformat()
        if self.completed_at is None:
            self.completed_at = datetime.now(timezone.utc).isoformat()
        if self.metadata is None:
            self.metadata = {}


class ExecutionDecisionConnector:
    """
    Bridge Execution results to canonical Decision/Event/Memory paths.

    Semantics:
      EXECUTION ≠ AUTHORIZATION
      RECORDED ≠ USED
      UNKNOWN ≠ VERIFIED
    """

    def __init__(self, mcp_endpoint: str = "http://localhost:5002"):
        self.mcp_endpoint = mcp_endpoint
        self.memory_writer = MemoryWriter() if MemoryWriter else None

    def connect_execution_to_canonical_paths(
        self,
        execution: ExecutionResult,
        decision_context: dict,
        approved_by: str = "system:phase8-7-connector"
    ) -> dict:
        """
        Main entry point: Execution → Decision → Event → Memory.

        Does NOT assume Execution SUCCESS = Authorization.
        Records actual observed state, not auto-approval.

        Args:
            execution: ExecutionResult from Execution Provider
            decision_context: {
                "title": str,
                "rationale": str,
                "impact": str,
                "related_events": [str],
                "related_documents": [str],
            }
            approved_by: who made the execution decision (default: system)

        Returns:
            {
                "status": "connected" | "partial" | "failed",
                "execution_id": str,
                "correlation_id": str,
                "decision_id": str,
                "event_id": Optional[str],
                "memory_id": Optional[str],
                "errors": [str],
                "trace": {...}
            }
        """
        result = {
            "status": None,
            "execution_id": execution.execution_id,
            "correlation_id": execution.correlation_id,
            "decision_id": None,
            "event_id": None,
            "memory_id": None,
            "errors": [],
            "trace": {
                "correlation_id": execution.correlation_id,
                "task_id": execution.task_id,
                "hab_request_id": execution.hab_request_id,
                "execution_id": execution.execution_id,
                "decision_id": None,
                "event_id": None,
                "memory_id": None,
            }
        }

        # Step 1: Write to canonical Decision Ledger
        decision_id, event_id = self._write_decision(
            execution, decision_context, approved_by, result["errors"]
        )
        result["decision_id"] = decision_id
        result["event_id"] = event_id
        result["trace"]["decision_id"] = decision_id
        result["trace"]["event_id"] = event_id

        if not decision_id:
            result["status"] = "failed"
            return result

        # Step 2: Write to Institutional Memory
        memory_id = self._write_to_memory(
            execution, decision_id, event_id, result["errors"]
        )
        result["memory_id"] = memory_id
        result["trace"]["memory_id"] = memory_id

        # Step 3: Determine overall status
        if decision_id and memory_id:
            result["status"] = "connected"
        elif decision_id:
            result["status"] = "partial"  # Decision recorded but memory write failed
        else:
            result["status"] = "failed"

        return result

    def _write_decision(
        self, execution: ExecutionResult, context: dict, approved_by: str, errors: list
    ) -> tuple:
        """
        Write execution result to canonical Decision Ledger.
        Companion event is auto-generated by mocka_decision_write.

        Returns: (decision_id, event_id)
        """
        try:
            # Alternatives: execution status options that were evaluated
            alternatives = [
                {"option": "continue_execution", "rejected_reason": "not selected"},
                {"option": "abort_execution", "rejected_reason": "not selected"},
                {"option": f"execute_and_record_as_{execution.status}",
                 "rejected_reason": "selected_option"}
            ]

            decision_payload = {
                "title": context.get("title", f"Execution {execution.execution_id} recorded"),
                "context": f"correlation_id={execution.correlation_id} task_id={execution.task_id}",
                "alternatives": alternatives,
                "decision": f"record_execution_status_{execution.status}",
                "rationale": context.get("rationale", f"Execution completed with status: {execution.status}"),
                "impact": context.get("impact", f"Execution {execution.status}, results recorded to decision ledger"),
                "related_events": context.get("related_events", []),
                "related_documents": context.get("related_documents", []),
                "approved_by": approved_by,
                "status": "Active",
            }

            # POST to MCP endpoint
            r = requests.post(
                f"{self.mcp_endpoint}/agent/mocka_decision_write",
                json=decision_payload,
                timeout=10
            )

            if r.status_code == 200:
                body = r.json()
                decision_id = body.get("decision_id")
                event_id = body.get("event_id")  # Auto-generated companion
                return decision_id, event_id
            else:
                errors.append(f"mocka_decision_write failed: {r.status_code} {r.text[:100]}")
                return None, None

        except requests.exceptions.ConnectionError:
            errors.append(f"MCP endpoint unreachable: {self.mcp_endpoint}")
            return None, None
        except Exception as e:
            errors.append(f"Decision write error: {str(e)}")
            return None, None

    def _write_to_memory(
        self, execution: ExecutionResult, decision_id: str, event_id: Optional[str], errors: list
    ) -> Optional[str]:
        """
        Write execution result to Institutional Memory.

        Returns: memory_id or None
        """
        if not self.memory_writer:
            errors.append("MemoryWriter not available (optional)")
            return None

        try:
            memory_entry = self.memory_writer.write_event(
                event={
                    "correlation_id": execution.correlation_id,
                    "task_id": execution.task_id,
                    "execution_id": execution.execution_id,
                    "hab_request_id": execution.hab_request_id,
                    "decision_id": decision_id,
                    "event_id": event_id,
                    "status": execution.status,
                    "output": execution.output,
                    "error": execution.error,
                    "started_at": execution.started_at,
                    "completed_at": execution.completed_at,
                    "metadata": execution.metadata,
                },
                memory_type=MemoryType.EPISODIC,
                source=Source.GOVERNANCE,
                tags=("execution", "phase8-7", execution.status)
            )

            # memory_entry is MemoryEntry dataclass with memory_id field
            memory_id = memory_entry.memory_id if hasattr(memory_entry, 'memory_id') else str(memory_entry)
            return memory_id

        except Exception as e:
            errors.append(f"Memory write error: {str(e)}")
            return None


def create_execution_result(
    status: str,
    output: str = None,
    error: str = None,
    metadata: dict = None,
    correlation_id: str = None,
    task_id: str = None,
    hab_request_id: str = None,
) -> ExecutionResult:
    """
    Factory function to create ExecutionResult from Execution Provider.
    """
    if correlation_id is None:
        correlation_id = f"CORR_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}_{uuid.uuid4().hex[:8]}"
    if task_id is None:
        task_id = f"TASK_{uuid.uuid4().hex[:8]}"
    if hab_request_id is None:
        hab_request_id = f"HAB_{uuid.uuid4().hex[:8]}"

    execution_id = f"EXEC_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}_{uuid.uuid4().hex[:8]}"

    return ExecutionResult(
        execution_id=execution_id,
        correlation_id=correlation_id,
        task_id=task_id,
        hab_request_id=hab_request_id,
        status=status,
        output=output,
        error=error,
        metadata=metadata or {},
    )
