// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2024 Mixesoft. All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
try{let J,E,ua;const ba=function(d){console.info(d)},ca=window,va=document,wb=va.documentElement,U=function(){},K=ba.call,{navigator:Ea,Event:x,Audio:xb,Blob:yb,Date:L,Promise:zb,open:y,close:Ua,parseInt:V,setTimeout:W,JSON:{stringify:Fa,parse:Va},URL:{createObjectURL:Ab,revokeObjectURL:Bb},chrome:{runtime:{sendMessage:Cb,getURL:Db},windows:{update:Eb},tabs:{create:Wa,update:Fb,query:Gb,getCurrent:Hb,remove:Ib,reload:Jb},action:{setTitle:Kb,setBadgeBackgroundColor:Lb,setBadgeText:Mb,setBadgeTextColor:Xa},
browsingData:{removeHistory:Nb,removeDownloads:Ya,removeCache:Ob,removeCacheStorage:Ga,removePasswords:Pb,removeFormData:Qb,removeLocalStorage:Ha,removeWebSQL:Ia,removeIndexedDB:Ja,removeFileSystems:Ka,removeAppcache:La,removeServiceWorkers:Rb,removeCookies:Za},history:{search:Sb},i18n:{getMessage:I}}}=ca,X=K.bind(x.prototype.preventDefault);K.bind(x.prototype.stopPropagation);const Tb=K.bind(DocumentFragment.prototype.querySelector),Ub=K.bind(DocumentFragment.prototype.querySelectorAll),Vb=ca.crypto.getRandomValues.bind(ca.crypto),
Wb=K.bind(HTMLMediaElement.prototype.play);K.bind(Number.prototype.toString);const [v,$a,Xb,Yb,Zb]="createElement createDocumentFragment createElementNS createTextNode querySelector querySelectorAll".split(" ").map(d=>va[d].bind(va)),[t,ab,Ma,bb,u,cb,da,wa,F,db,ea,$b]="addEventListener removeEventListener focus click appendChild removeChild hasAttribute getAttribute setAttribute scrollTo removeAttribute attachShadow".split(" ").map(d=>K.bind(wb[d])),[fa,xa,,Na,O]=["slice","indexOf","startsWith","match",
"split"].map(d=>K.bind(String.prototype[d])),[eb,Oa,ac,Pa]=["push","join","indexOf","slice","forEach"].map(d=>K.bind(Array.prototype[d])),G=K.bind(Object.getOwnPropertyDescriptor(Node.prototype,"textContent").set),fb=String.fromCharCode,bc=L.now,Qa=Db(""),cc=[".html","_blank"],q=function(d){return cc[d]},ja=async function(d){return new zb((f,k)=>{W(f,d)})},ya=async function(d){let f;try{let k=Fa(d);f=await Cb(k)}catch(k){ba(k),0<xa(k,"context")&&window.location.reload()}return f},z=function(){return"https://www.hotcleaner.com/"},
r=function(d){return Tb(J,d)},za=function(d){return Ub(J,d)},sc=function(){let d,f;var k,b,n,Y,ka,la,Z,Aa,P,ma;const w=[],M={},na=function(a){let c=0,e=0;if(a&&a.offsetParent){do c+=a.offsetLeft,e+=a.offsetTop;while(a=a.offsetParent)}return[c,e]},H=function(a,c,e){a&&(a.classList.remove(c),a.classList.add(e))},Q=function(){ya({id:7,v:d})},oa=async function(){/Win/.test(Ea.platform)&&ya({id:15,v:"000E"}).then(a=>{})},pa=async function(a){R(null,null);S(!0,!0,null);let c=gb(),e=r("#"+a),g=da(e,"ac");
a=V(fa(a,1));e.className="wipe";await hb(a,c);await ja(250);g||F(e,"ac","");e.className="ghk";(28==a||d.p28)&&ib();S(!1,!1,null);R(0==a||25==a||28==a?"m8":"m7",500);1==a&&jb();await ja(500);g||ea(e,"ac");e.className="chk"},dc=function(a){if(a instanceof x&&a.isTrusted){a=this.parentElement.firstElementChild;let c=a.id;"p27"==c?Ua():"p5"==c&&0==da(a,"ac")?aa("m5b",pa,U,c,null,null,null):"p20"==c&&0==da(a,"ac")?aa("m20b",pa,U,c,null,null,null):pa(c)}},ec=async function(){S(!0,!0,null);R(null,null);
let a=gb();var c=d.dev?[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]:[0,1,2,3,4,5,6,7,8,9,10,11,12,25];let e=[];for(let g=0,l=c.length;g<l;g++){let h=c[g],p=r("#p"+h);da(p,"ac")&&(p.className="wipe",eb(e,p,h))}for(let g=0,l=e.length;g<l;g+=2)c=e[g+1],await hb(c,a),1==c&&jb(),await ja(25),e[g].className="ghk";d.p28&&ib();R("m7",1E3);W(()=>{if(d.p27)Ua();else{for(let g=0,l=e.length;g<l;g+=2)e[g].className="chk";S(!1,null,null)}},1E3)},hb=async function(a,c){c={since:c};13>a?
(c.originTypes={unprotectedWeb:!0,protectedWeb:!1,extension:!1},0==a?(await kb(!1),await ja(500)):1==a?await Nb(c):2==a?(await Ya(c),await Ya(c)):3==a?(await Ob(c),await Ga(c)):4==a?await ya({id:31}):5==a?await Pb(c):6==a?await Qb(c):7==a?await Ha(c):8==a?await Ia(c):9==a?await Ja(c):10==a?await Ka(c):11==a?await La(c):12==a&&await Rb(c)):19>a?(c.originTypes={unprotectedWeb:!1,protectedWeb:!0,extension:!1},13==a?await Za(c):14==a?await Ha(c):15==a?await Ia(c):16==a?await Ja(c):17==a?await Ka(c):18==
a&&(await Ga(c),await La(c))):25>a?(c.originTypes={unprotectedWeb:!1,protectedWeb:!1,extension:!0},19==a?await Za(c):20==a?await Ha(c):21==a?await Ia(c):22==a?await Ja(c):23==a?await Ka(c):24==a&&(await Ga(c),await La(c))):25==a&&(await ja(500),await kb(!0))},kb=async function(a){try{let c=await Hb(),e=await Gb(a?{active:!0}:{});for(let g=0,l=e.length;g<l;g++){let h=e[g];c.id!==h.id&&(a?await Jb(h.id):0==g?await Fb(h.id,{url:"chrome://newtab"}):await Ib(h.id))}a&&await Eb(c.windowId,{focused:!0})}catch(c){ba(c)}},
jb=function(){Sb({text:""}).then(a=>{if(a&&-1<a.length){a=a.length;try{0<a&&(Xa&&Xa({color:"#fff"}),Lb({color:[99<a?233:21,21,21,255]})),Mb({text:0<a?99<a?"99+":a+"":""}),Kb({title:0<a?"History records: "+a+"\nClick&Clean":"\nClick&Clean"})}catch(c){ba(c)}}}).catch(a=>{ba(a)})},fc=function(a){if(a instanceof x&&a.isTrusted){a=V(fa(this.previousElementSibling.id,1),10);let c=[7,8,10,14,15,17,20,21,23],e=3==E||4==E||5==E?"chrome://":ua;1==a?(a=0,y(z()+"clear-browsing-history"+q(0),q(1))):2==a?e+="downloads/":
3==a?(a=0,y(z()+"cache-viewer"+q(0),q(1))):4==a||13==a||19==a?(a=0,y(z()+"cookie-wiper"+q(0),q(1))):-1<ac(c,a)?e+=2==E?"settings/siteData":"settings/content/all":5==a?e+=2==E?"wallet/passwords":"password-manager/passwords":6==a?e+="settings/autofill/":9==a||16==a||22==a?e+="indexeddb-internals":11==a||18==a||24==a?(a=0,y(z()+"cache-viewer"+q(0),q(1))):12==a?e+="serviceworker-internals":26==a?e+="version":29==a?(a=0,y(z()+"security-features-using-the-context-menu"+q(0),q(1))):31==a&&(a=0,y(z()+"clickclean-quick-access-menu"+
q(0),q(1)));0<a&&Wa({url:e})}},gc=function(a){d.time=a;Q()},Ra=function(){let a=r("#timeType"),c=a.selectedIndex;d.timeType=c;9==c?H(a,"w255","w32"):H(a,"w32","w255");lb();Q()},lb=function(){var a=r("#time");9==d.timeType?(da(a.firstElementChild,"data-time")||hc(a.firstElementChild,d.time,1,gc),H(a,"nvw","dbk")):(H(a,"dbk","nvw"),(a=r("#cal"))&&H(a,"dbk","nvw"))},gb=function(){let a=d.timeType;return 10==a?1:0==a?f:9==a?d.time:bc()-36E5*[0,1,2,4,8,10,12,24,168][a]},qa=function(a){let c=r("#"+a),e=
{};da(c,"ac")?(ea(c,"ac"),e[a]=0):(F(c,"ac",!0),e[a]=1);a in d&&(d[a]=e[a],Q())},ic=function(a){a instanceof x&&a.isTrusted&&(a=this.id,d[a]?qa(a):"p5"==a?aa("m5a",qa,U,a,null,null,null):"p4"==a||"p13"==a||"p19"==a?aa("m5c",qa,U,a,null,null,null):"p20"==a?aa("m20a",qa,U,a,null,null,null):qa(a))},S=function(a,c,e){let g=r("#shade"),l=r("#clr");l.disabled=r("#reset0").disabled=r("#reset1").disabled=r("#reset2").disabled=r("#dev").disabled=a;e?g.classList.add(e):(g.classList.remove("shade-bg-default"),
g.classList.remove("shade-bg-white"));g.style.height=a?r("#tab").scrollHeight+"px":"";c?F(l,"ac",!0):ea(l,"ac")},R=function(a,c){let e=r("#msg");a?(G(e,I(a)+"!"),e.classList.add("top48"),e.t&&(clearTimeout(e.t),e.t=null),e.t=W(R,c)):e.classList.remove("top48")},aa=function(a,c,e,g,l,h,p){S(!0,!1,p?p:"shade-bg-default");let C=r("#alert");p=C.firstElementChild.nextElementSibling;let B=p.nextElementSibling.firstElementChild,A=B.nextElementSibling;const m=function(D){D instanceof x&&D.isTrusted&&(ha(),
c(g))},T=function(D){D instanceof x&&D.isTrusted&&(ha(),e(g))},ha=function(){H(C,"dbk","nvw");c&&ab(A,"click",m,!1);e&&ab(B,"click",T,!1);S(!1,null,null)};G(p,I(a));G(A,I(l?l:"b0"));G(B,I(h?h:"b1"));e?H(B,"nvw","ibk"):H(B,"ibk","nvw");H(C,"nvw","dbk");e&&(t(B,"click",T,!1),Ma(B));c&&(t(A,"click",m,!1),Ma(A))},N=function(a){a instanceof x&&a.isTrusted&&(a=a.target.id||this.id,"suprt"==a?y(z()+"security-and-privacy-software-feedback"+q(0)+"#chvjica",q(1)):"ytest"==a?y(z()+"clickclean-app"+q(0)+"#chvjica",
q(1)):"help"==a?y(z()+"clickclean-quick-start-guide"+q(0),q(1)):"logo"==a?y(z(),q(1)):"ssl"==a?y(z()+"secure_search"+q(0),q(1)):"Crbs"==a?y(Qa+"ectrb901"+q(0),q(1)):"ghsty"==a?y(2==E?"https://account.microsoft.com/privacy/activity-history?view=search":"https://myactivity.google.com/item",q(1)):"skins"==a?y(z()+"clickclean-appearance"+q(0),q(1)):"gperms"==a?y(2==E?z()+"how-to-secure-your-microsoft-account"+q(0):z()+"improve-your-google-account-security"+q(0),q(1)):"sync"==a?Wa({url:2==E?"edge://sync-internals/":
3==E||4==E||5==E?"opera://sync-internals":"https://www.google.com/settings/chrome/sync"}):"news"==a?y(z()+"privacy-and-security-news"+q(0),q(1)):y(2==E?z()+"clickclean-for-microsoft-edge"+q(0):z()+"clickclean_chrome"+q(0),q(1)))},lc=function(){let a=O(I("cleaner1"),";"),c=O(I("msg5"),";");O(I("share"),";");var e=new Uint8Array(1);Vb(e);e=e[0]%7;e=function(g,l,h,p){g=r("#"+g);l&&("web"==g.className?G(g.firstElementChild,l):G(g,l));h&&(g.title=h);p&&t(g,"click",p,!0)};e("logo","v"+d.ver,0,N);e("ytest",
"Privacy Test",0,N);e("Crbs",a[0],a[2],N);e("clr",a[3],0,ec);e("HsTy",a[4],a[5],function(){y(z()+"clear-browsing-history"+q(0),q(1))});e("suprt",a[6],0,N);e("help",a[7],0,N);e("reset0",a[8],a[13],Sa);e("reset1",a[9],a[13],Sa);e("reset2",a[10],a[13],Sa);e("dev",a[11],a[12],function(){d.dev?(d.dev=0,Q(),Ba()):aa("m4",function(){d.dev=1;Q();Ba()},U,null,null,null,null)});e("export",a[14],0,jc);e("import",a[15],0,kc);e("ghsty",a[16],a[16],N);e("sync",a[17],a[17],N);e("gperms",c[3],c[1],N);e("skins",a[18],
a[18],N);e("news",a[19],a[19],N)},Ba=function(){let a=r("#dev"),c=za(".dev"),e=d.dev?"nvw":"dbk",g=d.dev?"dbk":"nvw";for(let l=0;l<c.length;++l)H(c[l],e,g);d.dev?F(a,"ac",!0):ea(a,"ac")},Sa=function(a){a instanceof x&&a.isTrusted&&(db&&db(r("#tab"),0,0),a=V(fa(a.target.id||this.id,5),10),2!=a||d.p5?mb(a):aa("m5a",function(){mb(2)},U,null,null,null,null))},mb=function(a){var c;0==a?c=[10,0,1,1,1,0,0,0,0,0,0,0,0,0,0]:1==a?c=[10,0,1,1,1,0,0,1,0,1,1,1,1,1,1]:2==a&&(c=[10,0,1,1,1,1,1,1,1,1,1,1,1,1,1]);
d.timeType=c[0];d.time=c[1];d.p1=c[2];d.p2=c[3];d.p3=c[4];d.p4=c[5];d.p5=c[6];d.p6=c[7];d.p7=c[8];d.p8=c[9];d.p9=c[10];d.p10=c[11];d.p11=c[12];d.p12=c[13];for(c=0;14>c;c++)a=r("#p"+c),d[a.id]?F(a,"ac",!0):ea(a,"ac");d.p31=1;d.p32=1;F(r("#p31"),"ac",!0);F(r("#p32"),"ac",!0);r("#timeType").selectedIndex=d.timeType;Ra()},ib=function(){try{Wb(new xb("fimg901/erased.ogg"))}catch(a){ba(a)}},jc=function(){var a=Va(Fa(d));for(let c of"gg gf go gp uf bn mc md mr ms mt ma uid dc ai au".split(" "))delete a[c];
a.ver="9.8.2.0";a=Fa({opt:a});a=new yb([a],{type:"text/plain;charset=UTF-8"});mc(a,"ClickClean-v9.8.2.0-Options")},kc=function(){nc(1E5,function(a){if("{"!=a.charAt(0)){a=Na(a,/.{1,2}/g);let e=[3,0,0,-3],g,l="";for(let h=0,p=a.length;h<p;h++)g=e[h%4],l=h+g<p?l+fb(V(a[h+g],16)):l+fb(V(a[h],16));a=l}try{a=Va(a)}catch(e){R("m12",1E3);return}a=a.opt;for(var c in a)void 0!=d[c]&&(d[c]=a[c]);d.ver="9.8.2.0";r("#timeType").selectedIndex=d.timeType;Ra();for(a=0;33>a;a++)c=r("#p"+a),d[c.id]?F(c,"ac",!0):ea(c,
"ac");d.wl&&400<d.wl.length&&(d.wl.length=400);Q();Ba();R("m8",1E3)})},nc=function(a,c){let e=r("#openAs");e&&cb(J,e);e=v("input");e.id="openAs";e.className="nvw";e.type="file";u(J,e);t(e,"change",function(g){if((g=g.target.files)&&1==g.length&&g[0].size<a){let l=new FileReader;l.onload=function(h){c(h.target.result)};l.readAsText(g[0])}else R("m12",1E3)},!1);bb(e)},mc=function(a,c){S(!0,null,null);let e=v("a");e.href=Ab(a);F(e,"download",c);bb(e);W(function(){Bb(e.href);S(!1,null,null)},2E3)},hc=
function(a,c,e,g){var l=O(I("calendar"),";");k=Pa(l,0,12);b=Pa(l,12,19);n=Pa(l,19,26);Y=0;ka=l[26];la=l[27];Z=l[28];Aa=l[29];P=l[30];ma=l[31];eb(w,{t:"l",r:Oa(n,"|"),p:function(h,p){return h},g:function(h){return n[h.getDay()]}},{t:"Y",r:"19\\d{2}|20\\d{2}",p:function(h,p){h.setFullYear(Number(p));return h},g:function(h){return h.getFullYear()}},{t:"F",r:Oa(k,"|"),p:function(h,p){for(let C=0;12>C;C++)if(k[C]==p)return h.setMonth(C),h},g:function(h){return k[h.getMonth()]}},{t:"d",r:"0[1-9]|[12][0-9]|3[01]",
p:function(h,p){h.setDate(Number(p));h.getDate()!=p&&h.setDate(0);return h},g:function(h){h=h.getDate();return(10>h?"0":"")+h}},{t:"h",r:"[0-1][0-9]|2[0-3]",p:function(h,p){h.setHours(Number(p));h.getHours()!=p&&h.setHours(0);return h},g:function(h){h=h.getHours();return(10>h?"0":"")+h}},{t:"e",r:"[0-4][0-9]|5[0-9]",p:function(h,p){h.setMinutes(Number(p));h.getMinutes()!=p&&h.setMinutes(0);return h},g:function(h){h=h.getMinutes();return(10>h?"0":"")+h}},{t:"s",r:"[0-4][0-9]|5[0-9]",p:function(h,p){h.setSeconds(Number(p));
h.getSeconds()!=p&&h.setSeconds(0);return h},g:function(h){h=h.getSeconds();return(10>h?"0":"")+h}});for(l=0;l<w.length;l++)M[w[l].t]=w[l];a.onDateChanged=g;a.showTime=e;nb(a,c?new L(c):new L);a.oncut=function(h){X(h)};a.oncontextmenu=function(h){X(h)};a.ondragstart=function(h){X(h)};a.onkeydown=function(h){Ma(this.nextElementSibling);X(h)};a.onclick=function(h){X(h)};t(a,"mouseup",oc,!1);e&&(t(a.nextElementSibling,"mousedown",ob,!1),t(a.nextElementSibling,"mouseup",pb,!1),t(a.nextElementSibling.nextElementSibling,
"mousedown",ob,!1),t(a.nextElementSibling.nextElementSibling,"mouseup",pb,!1))},nb=function(a,c){a.showTime||(c=qb(c));let e=c.getTime();F(a,"data-time",e);a.value=rb(c,wa(a,"data-format"));a.onDateChanged(e)},sb=function(){r("#cal").style.display="none"},pc=function(a){nb(this.parentElement.e_input,new L);sb()},tb=function(a,c){let e="^",g={},l=0;for(let p=0;p<c.length;p++){var h=c.charAt(p);M[h]?(g[h]=++l,e+="("+M[h].r+")"):e=" "==h?e+"\\s":e+((Na(h,/[\w\d]/)?"":"\\")+h)}if(!Na(a,new RegExp(e+"$")))return 0;
a=new L;a.setDate(1);for(c=0;c<w.length;c++)h=w[c].t,g[h]&&(h=RegExp["$"+g[h]],a=w[c].p(a,h));return a},ub=function(a){const c=function(ia,Ca,ra,qc){let Da=v("button");Ca&&(Da.className=Ca);G(Da,ra);u(ia,Da);t(Da,"click",function(Ta){Ta instanceof x&&Ta.isTrusted&&qc(Ta)},!1)};var e=function(ia,Ca){let ra=v("div");ra.className="arrow"+(Ca?"Left":"Right");ra.style.display="inline-block";u(ia,ra)};let g=r("#cal");var l=g.e_input,h=wa(l,"data-format");let p=new L;h=tb(l.value,h);a||=h;l.showTime||(a=
qb(a));let C=new L(a);C.setDate(1);C.setDate(1-(7+C.getDay()-Y)%7);l=$a();let B,A;B=v("table");B.id="calCtrls";A=v("tr");u(B,A);var m=v("td");m.className="calCtrl";m.title=ka;m.time=sa(a,-1,"FullYear");t(m,"click",ta,!1);u(A,m);e(m,1);e(m,1);m=v("td");m.className="calCtrl";m.title=Z;m.time=sa(a,-1,"Month");t(m,"click",ta,!1);u(A,m);e(m,1);m=v("th");G(m,k[a.getMonth()]+" "+a.getFullYear());u(A,m);m=v("td");m.className="calCtrl";m.title=Aa;m.time=sa(a,1,"Month");t(m,"click",ta,!1);u(A,m);e(m,0);m=v("td");
m.className="calCtrl";m.title=la;m.time=sa(a,1,"FullYear");t(m,"click",ta,!1);u(A,m);e(m,0);e(m,0);u(l,B);B=v("table");B.id="calGrid";A=v("tr");u(B,A);for(e=0;7>e;e++)m=v("th"),G(m,b[(Y+e)%7]),u(A,m);let T,ha,D=new L(C);for(;D.getMonth()==a.getMonth()||D.getMonth()==C.getMonth();){A=v("tr");for(let ia=0;7>ia;ia++){e=[];T=D.getDate();m=D.getMonth();ha=D.getYear();D.getMonth()!=a.getMonth()&&(e[e.length]="calOtherMonth");if(0==D.getDay()||6==D.getDay())e[e.length]="calWeekend";ha==p.getYear()&&m==p.getMonth()&&
T==p.getDate()&&(e[e.length]="calToday");ha==h.getYear()&&m==h.getMonth()&&T==h.getDate()&&(e[e.length]="calSelected");m=v("td");G(m,T);m.className=Oa(e," ");m.time=sa(D);u(A,m);t(m,"click",ta,!1);D.setDate(++T)}u(B,A)}u(l,B);c(l,"calBtn",P,pc);c(l,"calBtn",ma,sb);if(g.firstElementChild)for(a=0;4>a;a++)cb(g,g.firstElementChild);u(g,l)},sa=function(a,c,e){let g=new L(a);c&&(g["set"+e](a["get"+e]()+c),g.getDate()!=a.getDate()&&g.setDate(0));return g.valueOf()},ta=function(a){if(a instanceof x&&a.isTrusted){a=
r("#cal");let c=a.e_input,e=this.time,g=new L(e);"calCtrl"==this.className?ub(g):(c.value=rb(g,wa(c,"data-format")),F(c,"data-time",e),c.onDateChanged(e),a.style.display="none")}},rb=function(a,c){let e,g="";for(let l=0;l<c.length;l++)e=c.charAt(l),g+=M[e]?M[e].g(a):e;return g},ob=function(a){a instanceof x&&a.isTrusted&&(a=this.parentElement.firstElementChild,a.repeat=1E3,a.up="calUp"==this.className?1:0,vb(a))},pb=function(a){if(a instanceof x&&a.isTrusted){a=this.parentElement.firstElementChild;
a.repeat=0;let c=tb(a.value,wa(a,"data-format"));a.onDateChanged(c.getTime())}},vb=function(a){let c=a.repeat;if(c){1E3==c?c-=801:200>c&&(c-=25);100>c&&(c=100);a.repeat=c;var e=xa(a.value,"-");a.selStart||(a.selStart=e+2);var g=fa(a.value,a.selStart,a.selStart+2);g="0"==g.charAt(0)?V(g.charAt(1),10):V(g,10);g=a.up?g+1:g-1;a.selStart==e+2?23<g?g="00":0>g?g="23":10>g&&(g="0"+g):59<g?g="00":0>g?g="59":10>g&&(g="0"+g);a.value=fa(a.value,0,a.selStart)+g+fa(a.value,a.selStart+2);W(vb,c,a)}},rc=function(a){let c=
xa(a.value,"-"),e=a.selectionStart;if(e>c)return e<c+5?e=c+2:e<c+8?e=c+5:e<c+12&&(e=c+8),a.selStart=e,a.setSelectionRange(e,e+2),1;a.setSelectionRange(0,c-1);return 0},oc=function(a){if(a instanceof x&&a.isTrusted){a=r("#cal");let c=na(this);a||(a=v("button"),a.onselectstart=function(){return!1},a.id="cal",u(J,a));if(this.showTime){if(rc(this)){a.style.display="none";return}}else this.blur();0<a.offsetHeight&&a.e_input==this?a.style.display="none":(a.e_input=this,a.style.display="block",ub(0),a.style.top=
c[1]+this.offsetHeight+"px",a.style.left=c[0]+"px",a.style.display="block",a.focus())}},qb=function(a){a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a};ya({id:1}).then(a=>{0!==xa(a.u,Qa)&&(ca.location.href="about:blank");d=a.v;f=a.t;Ba();var c;let e;W(function(){va.title=I("m2")},1E3);lc();a=O(I("cleaner2"),";");e=za(".section");for(c=0;3>c;c++)G(e[c].childNodes[0],a[c]);e=za(".subtitle");for(c=0;3>c;c++)G(e[c],a[c+3]);e=r("#timeType");a=O(I("cleaner3"),";");G(r("#timeLabel"),
a[0]);for(var g=1;12>g;g++)c=v("option"),G(c,a[g]),u(e,c);e.selectedIndex=d.timeType;t(e,"change",function(l){l instanceof x&&l.isTrusted&&Ra()},!1);lb();a=O(I("cleaner4"),";");c=O(I("cleaner5"),";");for(g=0;34>g;g++){e=r("#p"+g);d[e.id]&&F(e,"ac",!0);t(e,"click",ic,!0);e=e.nextElementSibling;"more"==e.className&&(e.title=c[0],t(e,"click",fc,!0),e=e.nextElementSibling);if("run"==e.className||"del"==e.className)e.title=0==g?c[1]:25==g?c[2]:26==g?c[3]:27==g?c[4]:28==g?c[5]:a[g],t(e,"click",dc,!1),e=
e.nextElementSibling;e.title=33==g?"AI-based smart reminders":a[g];G(e,a[g])}t(J,"mousedown",function(l){l instanceof x&&l.isTrusted&&"select"!=l.target.localName&&"input"!=l.target.localName&&"p"!=l.target.localName&&X(l)},!1);a=za("label");for(let l=0,h=a.length;l<h;l++)t(a[l],"mouseup",function(p){p instanceof x&&p.isTrusted&&this.control&&W(function(C){C.control.blur()},100,this)},!1);e=r("#timeType");9==d.timeType?e.classList.add("w32"):e.classList.add("w255");oa()})},tc=function(){const [d,
f,k,b,n]=["div","button","id","class","label"],Y=[{t:1,l:d,a:[{n:k,v:"host"}],c:[{t:1,l:d,a:[{n:k,v:"page"}],c:[{t:1,l:d,a:[{n:k,v:"tab"},{n:b,v:"custom-scroll"}],c:[{t:1,l:d,a:[{n:k,v:"content"}],c:[{t:1,l:d,a:[{n:b,v:"section"},{n:k,v:"chrome"}],c:[{t:3,v:"i18"},{t:1,l:d,a:[{n:b,v:"float-rigth"}],c:[{t:1,l:n,a:[{n:k,v:"timeLabel"},{n:"for",v:"timeType"}]},{t:1,l:d,a:[{n:k,v:"time"}],c:[{t:1,l:"input",a:[{n:"type",v:"text"},{n:k,v:"timeInput"},{n:"data-format",v:"F d, Y - h:e:s"}]},{t:1,l:f,a:[{n:b,
v:"calUp"}],c:[{t:1,l:d,a:[{n:b,v:"arrowUp"}]}]},{t:1,l:f,a:[{n:b,v:"calDown"}],c:[{t:1,l:d,a:[{n:b,v:"arrowDown"}]}]}]},{t:1,l:"select",a:[{n:k,v:"timeType"}]}]}]},{t:1,l:d,a:[{n:b,v:"subtitle dev"}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p1"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p1"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p2"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,
v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p2"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p3"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p3"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p4"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p4"}]}]},{t:1,l:d,a:[{n:b,
v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p5"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p5"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p6"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p6"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p7"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,
v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p7"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p8"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p8"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p9"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p9"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,
v:"chk"},{n:k,v:"p10"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p10"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p11"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p11"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p12"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,
a:[{n:b,v:"label0 elps"},{n:"for",v:"p12"}]}]},{t:1,l:d,a:[{n:b,v:"subtitle dev"}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p13"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p13"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p14"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p14"}]}]},{t:1,l:d,a:[{n:b,
v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p15"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p15"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p16"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p16"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p17"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},
{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p17"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p18"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p18"}]}]},{t:1,l:d,a:[{n:b,v:"subtitle dev"}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p19"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},
{n:"for",v:"p19"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p20"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p20"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p21"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p21"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p22"}],
c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p22"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p23"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},{n:"for",v:"p23"}]}]},{t:1,l:d,a:[{n:b,v:"opt dev"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p24"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:f,a:[{n:b,v:"del"}]},{t:1,l:n,a:[{n:b,v:"label0 elps"},
{n:"for",v:"p24"}]}]},{t:1,l:d,a:[{n:b,v:"section"},{n:k,v:"actions"}],c:[{t:3,v:"i18"}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p0"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"run"}]},{t:1,l:n,a:[{n:b,v:"label1 elps"},{n:"for",v:"p0"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p27"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"run"}]},{t:1,l:n,a:[{n:b,v:"label1 elps"},{n:"for",v:"p27"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p25"}],c:[{t:1,
l:d}]},{t:1,l:f,a:[{n:b,v:"run"}]},{t:1,l:n,a:[{n:b,v:"label1 elps"},{n:"for",v:"p25"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p28"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"run"}]},{t:1,l:n,a:[{n:b,v:"label1 elps"},{n:"for",v:"p28"}]}]},{t:1,l:d,a:[{n:b,v:"section"},{n:k,v:"extra"}],c:[{t:3,v:"i18"}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p26"}],c:[{t:1,l:d}]},{t:1,l:n,a:[{n:b,v:"label2 elps"},{n:"for",v:"p26"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,
l:f,a:[{n:b,v:"web"},{n:k,v:"ghsty"}],c:[{t:1,l:d,a:[{n:b,v:"elps"}]}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p30"}],c:[{t:1,l:d}]},{t:1,l:n,a:[{n:b,v:"label2 elps"},{n:"for",v:"p30"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"web"},{n:k,v:"sync"}],c:[{t:1,l:d,a:[{n:b,v:"elps"}]}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p29"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:n,a:[{n:b,v:"label1 elps"},{n:"for",v:"p29"}]}]},{t:1,l:d,
a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"web"},{n:k,v:"gperms"}],c:[{t:1,l:d,a:[{n:b,v:"elps"}]}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p31"}],c:[{t:1,l:d}]},{t:1,l:f,a:[{n:b,v:"more"}]},{t:1,l:n,a:[{n:b,v:"label1 elps"},{n:"for",v:"p31"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"web"},{n:k,v:"skins"}],c:[{t:1,l:d,a:[{n:b,v:"elps"}]}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p32"}],c:[{t:1,l:d}]},{t:1,l:n,a:[{n:b,v:"label2 elps"},
{n:"for",v:"p32"}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"web"},{n:k,v:"news"}],c:[{t:1,l:d,a:[{n:b,v:"elps"}]}]}]},{t:1,l:d,a:[{n:b,v:"opt"}],c:[{t:1,l:f,a:[{n:b,v:"chk"},{n:k,v:"p33"}],c:[{t:1,l:d}]},{t:1,l:n,a:[{n:b,v:"label2 elps"},{n:"for",v:"p33"}]}]},{t:1,l:d,a:[{n:b,v:"opt opt-export"}],c:[{t:1,l:f,a:[{n:b,v:"btns trp"},{n:k,v:"export"}]},{t:1,l:f,a:[{n:b,v:"btns trp"},{n:k,v:"import"}]}]}]},{t:1,l:d,a:[{n:k,v:"shade"}]}]},{t:1,l:d,a:[{n:k,v:"ftr"}],c:[{t:3,v:" "},{t:1,l:d,a:[{n:k,
v:"suprt"}]},{t:1,l:f,a:[{n:b,v:"btns blk start"},{n:k,v:"reset0"}]},{t:1,l:f,a:[{n:b,v:"btns blk mid"},{n:k,v:"reset1"}]},{t:1,l:f,a:[{n:b,v:"btns blk end"},{n:k,v:"reset2"}]},{t:1,l:f,a:[{n:b,v:"btns blk"},{n:k,v:"dev"}]},{t:1,l:d,a:[{n:b,v:"btr"}],c:[{t:1,l:f,a:[{n:b,v:"btn yel"},{n:k,v:"HsTy"}]},{t:1,l:f,a:[{n:b,v:"btn red"},{n:k,v:"clr"}]}]}]},{t:1,l:d,a:[{n:k,v:"msg"}]},{t:1,l:d,a:[{n:k,v:"hdr"},{n:b,v:"bg0"}],c:[{t:1,l:f,a:[{n:k,v:"logo"}]},{t:1,l:f,a:[{n:k,v:"ytest"}]},{t:1,l:d,a:[{n:b,v:"btr"}],
c:[{t:1,l:f,a:[{n:k,v:"Crbs"}]},{t:1,l:f,a:[{n:k,v:"help"},{n:b,v:"btn yel"}]}]}]}]},{t:1,l:d,a:[{n:k,v:"alert"},{n:b,v:"nvw"}],c:[{t:1,l:"b",c:[{t:3,v:"Click&Clean"}]},{t:1,l:"p"},{t:1,l:"p",a:[{n:b,v:"text-right"}],c:[{t:1,l:f,a:[{n:b,v:"btn yel elps"}]},{t:1,l:f,a:[{n:b,v:"btn yel elps"}]}]}]}]}],ka=function(P,ma){let w,M,na;for(let H=0,Q=ma.length;H<Q;H++)if(w=ma[H],1==w.t){M=w.n?Xb("http://www.w3.org/2000/svg",w.l):v(w.l);for(let oa=0,pa=w.a&&w.a.length||0;oa<pa;oa++)na=w.a[oa],F(M,na.n,na.v);
w.c&&ka(M,w.c);u(P,M)}else 3==w.t&&u(P,Yb(w.v))},la=$a(),Z=v("link"),Aa=Zb("body");J=$b(Aa,{mode:"closed"});t(Z,"load",function(P){P instanceof x&&P.isTrusted&&(ka(la,Y),u(J,la),sc())},!1);F(Z,"rel","stylesheet");F(Z,"href",Qa+"fcss901/ecleaner901.css");u(J,Z)};t(ca,"DOMContentLoaded",function(d){if(d instanceof x&&d.isTrusted){d="Google Chrome;Microsoft Edge;Opera;Opera GX;Opera Crypto;Yandex;Brave".split(";");let k="chrome:// edge:// opera:// opera:// opera:// browser://".split(" ");if("userAgentData"in
Ea){var f=Ea.userAgentData;f=f.fullVersionList||f.brands||[];for(const b of f){f=b.brand;for(let n=0,Y=d.length;n<Y;n++)if(f==d[n]){E=n+1;ua=k[n];break}}}E=E||1;ua=ua||k[0];tc()}},!1);t(ca,"contextmenu",function(d){X(d)},!1)}catch(J){console.info(J)};
