// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2024 Mixesoft. All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
try{let P,I;const za=function(r){console.info(r)},Y=window,D=document,na=function(){},n=Function.prototype.call,x=Event,{runtime:{sendMessage:Aa},i18n:{getMessage:Ba}}=chrome,K=Element.prototype,Z=String.prototype,fa=Array.prototype,aa=Node.prototype,F=D.createElement.bind(D),Ca=D.createElementNS.bind(D),Da=D.querySelector.bind(D),ha=D.createTextNode.bind(D),ia=D.createDocumentFragment.bind(D),y=n.bind(EventTarget.prototype.addEventListener),oa=n.bind(x.prototype.stopPropagation);n.bind(x.prototype.preventDefault);
const v=n.bind(aa.appendChild),ja=n.bind(aa.insertBefore),U=n.bind(aa.removeChild),pa=n.bind(K.hasAttribute),t=n.bind(K.getAttribute),E=n.bind(K.setAttribute),Q=n.bind(K.removeAttribute),qa=n.bind(K.querySelectorAll),Ea=K.attachShadow?n.bind(K.attachShadow):null,Fa=n.bind(DocumentFragment.prototype.querySelector),ra=n.bind(Z.slice),ka=n.bind(Z.indexOf),Ga=n.bind(Z.split),sa=n.bind(Z.match),G=n.bind(fa.indexOf),z=n.bind(fa.push),Ha=n.bind(fa.sort),Ia=JSON.stringify,V=parseInt,ta=Object.defineProperty,
R=Object.getOwnPropertyDescriptor(aa,"textContent"),Ja=R&&R.get?n.bind(R.get):na,A=R&&R.set?n.bind(R.set):na,Ka=chrome.runtime.getURL(""),La=".com .net google accounts doubleclick live login youtube".split(" "),k=function(r){return La[r]},S=async function(r){let B;try{let H=Ia(r);B=await Aa(H)}catch(H){za(H),0<ka(H,"context")&&window.location.reload()}return B},Ma=function(r){S({id:9,v:r})},m=function(r){return Fa(P,r)},Pa=function(){let r=-1;const B=function(){let a=[k(3)+"."+k(2)+k(0),k(2)+k(0)];
0==I||10==I?z(a,k(4)+k(1)):2==I||12==I?z(a,"youtube"+k(0)):(3==I||13==I)&&z(a,"youtube"+k(0),k(4)+k(1));return a},H=function(){return 9<I?/^google\.(com\.au|be|ca|ch|cn|de|dk|ee|es|fi|fr|gr|ie|co\.il|it|co\.jp|co.kr|lt|lv|nl|no|co\.nz|pl|pt|ru|se|com.tw|co\.uk)$/g:/^$/},J=function(){C(1);let a=m("#list0");for(;a.firstElementChild;)U(a,a.firstElementChild);for(a=m("#list1");a.firstElementChild;)U(a,a.firstElementChild);S({id:30}).then(b=>{let c=b[0];b=b[1];let e=[],d,f,g=0,p=0,q=0;if(0<c.length){for(let l=
0,h;h=c[l];l++)"."==h.charAt(0)&&(c[l]=ra(h,1));Ha(c,function(l,h){return l<h?-1:1});d=G(b,c[0]);for(let l=0,h;h=c[l];l++)f!=h&&(0<g&&(0>d?(z(e,g),p+=g):(b[d+1]=g,q+=g),g=0),d=G(b,h),0>d&&z(e,h)),g++,f=h;0<g&&(0>d?(z(e,g),p+=g):(b[d+1]=g,q+=g))}if(-1<G(b,k(2)+k(0))){let l=B(),h=H(),u=2;e=e.filter(function(L){if(2==u){if(0>G(l,L)&&null==sa(L,h))return u=1,!0;u=0;return!1}if(1==u)return u=2,!0;p-=L;u=2;return!1})}if(-1<G(b,k(5)+k(0))){let l=2;e=e.filter(function(h){if(2==l){if(h!=k(6)+"."+k(5)+k(0))return l=
1,!0;l=0;return!1}if(1==l)return l=2,!0;p-=h;l=2;return!1})}ua(0,e,1,1);ua(1,b,0,0);A(m("#cnt0")," ("+p+")");A(m("#cnt1")," ("+q+")");C(0)})},M=function(a){if(a instanceof x&&a.isTrusted){a=la(this,"on");let b=this.parentElement.nextElementSibling.children;for(let c=0,e;e=b[c];c++)ba(e.firstElementChild,"on",a),ba(e,"on",a)}},N=function(a){a instanceof x&&a.isTrusted&&(t(this.parentNode,"data-domain"),Ma({u:"https://www.hotcleaner.com/stay-logged-in-and-keep-settings-for-sites.html"}),oa(a))},da=
function(a){if(a instanceof x&&a.isTrusted){C(1);oa(a);let b=this.parentElement,c=t(b.parentNode,"data-id");a=t(b,"data-domain");let e=V(t(b,"data-count"),10),d;0==c&&(d=[a]);S({id:31,v:d}).then(()=>{0==c&&(U(b.parentElement,b),ca(c,-e),C(0))})}},w=function(a){if(a instanceof x&&a.isTrusted){C(1);var b=this.parentElement.nextElementSibling;a=qa(b,".item[on]");if(0<a.length){let c=[],e=t(b,"data-id"),d=0;for(let f=0,g;g=a[f];f++)b=t(g,"data-domain"),z(c,b),d+=V(t(g,"data-count"),10),U(g.parentElement,
g);S({id:31,v:c}).then(()=>{ca(e,-d);C(0)})}else C(0)}},T=function(a){a instanceof x&&a.isTrusted&&(C(1),ea(1,0)&&(O(),J()))},W=function(a){a instanceof x&&a.isTrusted&&(C(1),ea(0,1)&&(O(),J()))},X=function(a){let b,c=[];for(let e=0,d=a.length;e<d;e+=2)b=a[e],0>G(c,b)&&z(c,b,0);return c},ma=function(a){if(-1<G(a,k(2)+k(0))){let b=B(),c=H(),e,d=[];for(let f=0,g=a.length;f<g;f+=2)e=a[f],0>G(b,e)&&0>G(d,e)&&(sa(e,c)||z(d,e,0));z(d,k(2)+k(0),0);return d}return a},O=function(){let a=m("#list1").children,
b=a.length;if(3E3<b)alert("Maximum number of 3000 whitelisted domains exceeded!"),C(0);else{let c=[],e;for(let d=0;d<b;d++)e=a[d],"item"==e.className&&z(c,t(e,"data-domain"),0);c=X(c);c=ma(c);S({id:35,v:c}).then(()=>{C(0)})}},ea=function(a,b){let c=qa(m("#list"+a),".item[on]"),e=c.length;if(0<e){let d=[];for(let f=0,g;g=c[f];f++)z(d,U(g.parentNode,g));va(a,b,d)}return e},ca=function(a,b){a=m("#cnt"+a);b=V(ra(Ja(a),2),10)+b;0>b&&(b=0);A(a," ("+b+")")},la=function(a,b){let c=pa(a,b);c?Q(a,b):E(a,b,
"");return!c},ba=function(a,b,c){c?E(a,b,""):Q(a,b)},Na=function(a){if(a instanceof x&&a.isTrusted){var b=pa(this,"on");if(a.shiftKey){if(0>r&&(r=this.parentNode.firstElementChild),a=!b,b=r,this&&b){var c=this;t(c,"data-domain")>t(b,"data-domain")&&(c=b,b=this);for(;c&&t(c,"data-domain")<=t(b,"data-domain");)ba(c,"on",a),ba(c.firstElementChild,"on",a),c=c.nextElementSibling}}else la(this.firstElementChild,"on"),la(this,"on");r=this}},xa=function(a,b,c,e,d){let f,g,p,q,l,h,u;f=F("div");g=F("button");
p=F("div");q=F("label");l=F("button");h=F("button");f.className="item"+(d?" subsvc":"");g.className="chk";q.className="label elps";h.className="btn link";l.className="btn del";l.title="Delete Cookies";E(f,"data-domain",a);E(f,"data-count",b);u&&E(f,"data-brand",u);e&&(E(g,"on",""),E(f,"on",""));u=wa(a);c?A(q,a+" ("+b+")"):u?(A(q,u),ta(g,"brand",{configurable:!1,enumerable:!1,writable:!1,value:u})):A(q,a);v(g,p);v(f,g);v(f,q);v(f,l);v(f,h);y(l,"click",da,!1);y(h,"click",N,!1);y(f,"click",Na,!1);return f},
ua=function(a,b,c,e){a=m("#list"+a);let d,f=ia();for(let g=0,p;p=b[g];g+=2)d=xa(p,b[g+1],c,e,!1),v(f,d);v(a,f)},va=function(a,b,c){let e=m("#list"+b),d,f;let g=0;for(let l=0,h;h=c[l];l++){var p=!0;d=t(h,"data-domain");f=h.brand||wa(d);for(let u=0,L;L=e.children[u];u++){var q=t(L,"data-domain");if(d==q){p=!1;break}else if(d<q){p=V(t(h,"data-count"),10);g+=p;q=h.firstElementChild.nextElementSibling;0==b?A(q,d+" ("+p+")"):f?(A(q,f),Q(h,"on"),Q(h.firstElementChild,"on")):A(q,d);ja(e,h,L);p=!1;break}}p&&
(p=V(t(h,"data-count"),10),g+=p,q=h.firstElementChild.nextElementSibling,0==b?A(q,d+" ("+p+")"):f?(A(q,f),Q(h,"on"),Q(h.firstElementChild,"on")):A(q,d),v(e,h))}0<g&&(ca(a,-g),ca(b,g))},ya=function(){return[["Consent Cookies","Select this option to keep consent settings\nfor some websites\nso you don't have to consent every time.","c.com"],["Google Account & Services","Select this option to stay signed in to\nGoogle Account and related services.",k(2)+k(0)],["Facebook","Facebook","facebook.com"],["Twitter",
"Twitter","twitter.com"],["Yahoo","Yahoo","yahoo.com"],["Microsoft","SkyDrive, Live Mail, …",k(5)+k(0)]]},wa=function(a){let b=ya(),c;for(let e=0,d;d=b[e];e++)if(-1<ka(d[2],a)){c=d[0];break}return c},Oa=function(a){if(a instanceof x&&a.isTrusted){a=this.domains||a.target.domains;a:{var b=a;let c=m("#list1").children,e;for(let d=0,f;f=c[d];d++)if(e=t(f,"data-domain"),e==b){b=f;break a}b=0}b||(b=xa(a,0,0,0,!1),va(0,1,[b]),O(),J())}},C=function(a){m("#shade").className=a?"dbk":"nvw"};(function(){let a=
Ga(Ba("cookies"),";"),b=m("#sel0");b.title=a[0];b=m("#sel1");b.title=a[0];b=m("#t11");ja(b,ha(a[1]),b.firstElementChild);b=m("#t12");ja(b,ha(a[2]),b.firstElementChild);b=m("#ref");b.title=a[3];b=m("#del0");b.title=a[4];y(m("#sel0"),"click",M,!1);y(m("#sel1"),"click",M,!1);y(m("#ref"),"click",function(c){c instanceof x&&c.isTrusted&&J()},!1);y(m("#del0"),"click",w,!1);y(m("#toc0"),"click",T,!1);y(m("#toc1"),"click",W,!1)})();J();(function(){let a=m("#services"),b=ya();let c,e=ia();for(let f=0,g=b.length;f<
g;f++){var d=b[f];c=F("button");c.className="btn float-left";c.title=d[1];ta(c,"domains",{configurable:!1,enumerable:!1,writable:!1,value:d[2]});d=new Image;d.className="mt3";d.src="fimg901/fav/"+(f+1)+".png";v(c,d);y(c,"click",Oa,!0);v(e,c)}v(a,e)})()},Qa=function(){const r=[{t:1,l:"div",a:[{n:"id",v:"host"}],c:[{t:1,l:"div",a:[{n:"class",v:"view"},{n:"id",v:"view0"}],c:[{t:1,l:"div",a:[{n:"class",v:"hdr"},{n:"id",v:"hdr0"}],c:[{t:1,l:"button",a:[{n:"id",v:"sel0"},{n:"class",v:"chk"},{n:"title",
v:"t10"}],c:[{t:1,l:"div"}]},{t:1,l:"label",a:[{n:"class",v:"label elps"},{n:"id",v:"t11"}],c:[{t:1,l:"span",a:[{n:"id",v:"cnt0"}]}]},{t:1,l:"button",a:[{n:"class",v:"btn"},{n:"id",v:"del0"},{n:"title",v:"t14"}]},{t:1,l:"button",a:[{n:"class",v:"btn"},{n:"id",v:"ref"},{n:"title",v:"t13"}]}]},{t:3,v:" "},{t:1,l:"div",a:[{n:"class",v:"list"},{n:"id",v:"list0"},{n:"data-id",v:"0"}]}]},{t:1,l:"button",a:[{n:"id",v:"toc1"}]},{t:1,l:"button",a:[{n:"id",v:"toc0"}]},{t:1,l:"div",a:[{n:"class",v:"view"},{n:"id",
v:"view1"}],c:[{t:1,l:"div",a:[{n:"class",v:"hdr"},{n:"id",v:"hdr1"}],c:[{t:1,l:"button",a:[{n:"id",v:"sel1"},{n:"class",v:"chk"},{n:"title",v:"t10"}],c:[{t:1,l:"div"}]},{t:1,l:"label",a:[{n:"class",v:"label elps"},{n:"id",v:"t12"}],c:[{t:1,l:"span",a:[{n:"id",v:"cnt1"},{n:"class",v:"nvw"}]}]},{t:1,l:"div",a:[{n:"id",v:"services"}]}]},{t:1,l:"div",a:[{n:"class",v:"list"},{n:"id",v:"list1"},{n:"data-id",v:"1"}]}]},{t:1,l:"div",a:[{n:"id",v:"shade"}]}]}],B=function(N,da){let w,T,W;for(let X=0,ma=da.length;X<
ma;X++)if(w=da[X],1==w.t){T=w.n?Ca("http://www.w3.org/2000/svg",w.l):F(w.l);for(let O=0,ea=w.a&&w.a.length||0;O<ea;O++)W=w.a[O],E(T,W.n,W.v);w.c&&B(T,w.c);v(N,T)}else 3==w.t&&v(N,ha(w.v))},H=Da("body"),J=ia(),M=F("link");P=Ea(H,{mode:"closed"});y(M,"load",function(N){N instanceof x&&N.isTrusted&&(B(J,r),v(P,J),Pa())},!1);E(M,"rel","stylesheet");E(M,"href",Ka+"fcss901/ecookies901.css");v(P,M)},Ra=function(r){r instanceof x&&r.isTrusted&&S({id:1}).then(B=>{I=B.v.dc;0===ka(B.u,"https://www.hotcleaner.com/")&&
Qa()})};Y.self==Y.top?Y.location.href="https://www.hotcleaner.com/cookie-wiper.html":y(Y,"DOMContentLoaded",Ra,!0)}catch(P){console.info(P)};
