// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2024 Mixesoft. All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
try{const b=window,t=navigator.language||"en",l={},r=function(){b.location.href="https://www.hotcleaner.com/";return[null,null]},w=function(){var a=b.location.hash;if(a){b.location.hash="";a=a.slice(1).split("-");let c=parseInt(a[0])-Date.now(),h=parseInt(a[1]);a=parseInt(a[2]);return 2100>c?[h,a]:r()}return r()},[n,q]="data:"==b.location.protocol?JSON.parse("ARGS"):w(),x=function(a){a.stopPropagation();a.preventDefault()},g=function(a,c){return Math.floor(Math.random()*(c+1-a))+a},u=function(){b.outerWidth==
l.w&&b.outerHeight==l.h||b.resizeTo(l.w,l.h);setTimeout(u,2E3)},y=function(){var a=10<n?n-10:n,c=2==a||5==a||8==a;let h=4==a||5==a||6==a,f=g(1,54),m=b.screen.availWidth,e=b.screen.availHeight,d=l.w=b.outerWidth,k=l.h=b.outerHeight;c=c?parseInt((m-d-f)/2,10):1==a||4==a||7==a?f:m-d-f;a=h?parseInt((e-k-f)/2,10):1==a||2==a||3==a?f:e-k-f;d>m&&(c=0);k>e&&(a=0);1>c&&(c=0);1>a&&(a=0);b.moveTo(c,a);setTimeout(u,2E3)},z=function(a){let c=g(0,1),h=g(0,359),f=g(133,255),m=g(13,55),e=g(1,21);g(21,55);let d=g(89,
100),k="hsl(0deg 0% "+d+"%)";a=a.sheet;a.cssRules[1].style.background="hsl("+h+"deg "+m+"% "+d+"%)";a.cssRules[1].style.color="hsl(0deg 0% "+e+"%)";a.cssRules[7].cssRules[0].style.background="hsl("+h+"deg "+m+"% "+e+"%)";a.cssRules[7].cssRules[0].style.color=k;a.cssRules[6].style.color=k;a.cssRules[6].style.background="hsl("+(c?g(350,360):g(210,220))+"deg,79%,"+g(34,55)+"%)";return["rgb("+f+",0,0)",k]},A=function(){return"https://www.hotcleaner.com/"+(t.startsWith("de")?["browserverlauf-loschen",
"browser-update-scanner-de"]:t.startsWith("ja")?["clear-browsing-history-ja","browser-update-scanner-ja"]:["clear-browsing-history","browser-update-scanner"])[q-3]+".html"},D=function(a){a=(chrome&&chrome.i18n&&chrome.i18n.getMessage("msg"+q)||"I18N").split(";");let c=document.createDocumentFragment(),h=document.createElement("main"),f=document.createElement("div"),m=document.createElement("h4"),e=document.createElement("a");let d,k=document.body.attachShadow({mode:"closed"});var p=document.querySelector('[rel="stylesheet"]')||
document.querySelector("style");k.appendChild(p);const [B,C]=z(p);p=document.createElementNS("http://www.w3.org/2000/svg","svg");p.setAttributeNS(null,"viewBox","0 0 16 16");d=document.createElementNS("http://www.w3.org/2000/svg","path");d.setAttributeNS(null,"fill",B);d.setAttributeNS(null,"d","M8 0a.67.67.0 00-.25.05L1.4 2.59c-.24.1-.4.33-.4.58v3.09c0 4.26 2.67 8.09 6.76 9.7.15.06.33.06.48.0A10.47 10.47.0 0015 6.25v-3.1a.63.63.0 00-.4-.57L8.25.05A.67.67.0 008 0z");p.appendChild(d);d=document.createElementNS("http://www.w3.org/2000/svg",
"path");d.setAttributeNS(null,"fill",C);d.setAttributeNS(null,"d","M8 4.29A1.75 1.75.0 006.25 6.04 1.75 1.75.0 108 4.29zm.06 4.17a3.73 3.73.0 00-3.54 2.39 4.5 4.5.0 006.96.0 3.73 3.73.0 00-3.42-2.4z");p.appendChild(d);m.textContent=a[0];e.href=l.u=A();e.target="_blank";e.rel="noopener";e.textContent=a[1];e.setAttribute("autofocus","");f.appendChild(p);f.appendChild(m);h.appendChild(f);h.appendChild(e);c.appendChild(h);k.appendChild(c);e.addEventListener("click",function(v){v.isTrusted&&(v.target.href==
l.u?b.close():b.open(l.u))},!0)};"number"==typeof n&&"number"==typeof q&&-1<n&&20>n&&-1<q&&5>q?(0!=n&&10!=n&&y(),2<q&&b.addEventListener("load",D,!0),b.addEventListener("contextmenu",function(a){x(a)},!0)):r();setTimeout(function(){b.close()},105E5)}catch(b){console.info(b)};
