// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2024 Mixesoft. All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
try{let F,h,p;const G=function(c){console.info(c)},H=window,V=document,na=V.documentElement,A=G.call,{Event:I,Audio:fa,Image:ha,navigator:W,parseInt:M,setTimeout:N,close:oa,open:k,JSON:{stringify:pa},Math:{random:qa,floor:ra},chrome:{runtime:{sendMessage:sa,getURL:X},tabs:{create:r,query:Y,reload:ta,remove:ua,update:ia},windows:{create:va,update:wa},i18n:{getMessage:xa}}}=H;A.bind(I.prototype.stopPropagation);A.bind(I.prototype.preventDefault);const ya=A.bind(DocumentFragment.prototype.querySelector),
za=A.bind(HTMLMediaElement.prototype.play),[x,ja,Aa]=["createElement","createDocumentFragment","querySelector","querySelectorAll"].map(c=>V[c].bind(V)),[t,Ba,Z,O,,ka,Ca]="appendChild removeChild insertBefore addEventListener removeEventListener setAttribute attachShadow".split(" ").map(c=>A.bind(na[c])),[Da,,,aa]="indexOf startsWith split slice match trim replace".split(" ").map(c=>A.bind(""[c]));["map","reduce","forEach"].map(c=>A.bind(Array.prototype[c]));const R=A.bind(Object.getOwnPropertyDescriptor(Node.prototype,
"textContent").set),Ea="hotcleaner https://www.  google.com .com/ .html _blank .html chrome://".split(" "),a=function(c){return Ea[c]},S=function(c,e){return ra(qa()*(e+1-c))+c},y=async function(c){let e;try{let f=pa(c);e=await sa(f)}catch(f){G(f),0<Da(f,"context")&&window.location.reload()}return e},ba=function(c){return xa(c).split(";")},la=function(c){return M(H.screen.availHeight/2-c/2)},ma=function(c){return M(H.screen.availWidth/2-c/2)},T=function(c){let e;3==c||4==c?(e="https://",e=2==h?e+
("blogs.windows"+a(4)+"msedgedev/author/msedgeteam/"):3==h||4==h||5==h?e+("blogs.opera"+a(4)+"desktop/"):6==h?e+"browser.yandex.ru/blog":7==h?e+"brave.com/latest/":e+(3==c?"blog.google/products/chrome/":"chromereleases.googleblog"+a(4))):5==c?(e=p,e=3==h||4==h||5==h?a(8)+"about/credits/":e+"credits/"):6==c&&(e=p,e=3==h||4==h||5==h?e+"about/":e+"version/");return e},B=function(c){let e,f=a(1)+a(0)+a(4);1==c?e=f+"clear-browsing-history"+a(5):2==c?e=f+"cookie-wiper"+a(5):3==c?e=f+"clickclean-private-mode"+
a(5):4==c&&(e=f+"browser-update-scanner"+a(5));return e},Fa=function(){Y({active:!0,windowType:"normal"}).then(c=>{let e=B(3),f;c&&0<c.length&&(f=c[0].url||"");f&&(e+="#"+encodeURIComponent(f));k(e,a(6))}).catch(G)},ca=async function(c,e,f,P,J,D){try{let n=X(c),C=await Y({url:n});C&&0<C.length?(await wa(C[0].windowId,{focused:!0}),await ia(C[0].id,{active:!0})):await va({type:"popup",url:n,focused:!0,top:e,left:f,width:P,height:J});D&&oa()}catch(n){G(n)}},da=()=>{ca("ecleaner901"+a(7),la(500),
ma(770),770,500,!0)},Q=function(c){return ya(F,c)},Ha=function(){let c,e=!1,f="menu0";const P=function(d){if(d instanceof I&&d.isTrusted){let b=d.target.id;"menu3"==b?k(X("ectrb901"+a(7)),a(6)):f!=b&&(f&&(Q("#"+f).className="nav"),f=b,d.target.className="nav act",J(b,null))}},J=function(d,b){b=b||Q("#box");let m=ba(d),q=ja();let l,g;let v,u,w,ea,K="menu0"==d?[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,7,0,"help.png",27,3,"violet",
"cache.png",3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,7,0,"help.png",27,0,"blue","quickscan.png",8,3,"violet","security.png",14,7,0,"test.png",28,0,"choko","cookie.png",15,7,0,"trash1.png",16,7,0,"help.png",27,0,"seawave",c?"cleanup.png":"memory.png",c?12:13,3,"violet","downloads.png",9,7,0,"trash1.png",10,0,"red","defender.png",21,0,"teal","report.png",17,0,"magenta","options.png",18,7,0,"themes.png",19,0,"green","updates.png",20,7,0,"browser.png",20,0,"carbon","incognito.png",
11]:"menu1"==d?[3,"seawave","plugins.png",0,3,"green","extensions.png",1,7,0,"apps.png",2,3,"orange","experiments.png",3,3,"magenta","internals.png",4,0,"violet","dns.png",5,3,"violet","history.png",6,0,"violet","cache.png",7,0,"red","key.png",8,3,"blue","version.png",9,7,0,"arrow1.png",10,0,"red","conflicts.png",11,0,"teal","policies.png",12,0,"blue","releases.png",13,7,0,"calendar1.png",14,0,"blue","credits.png",15,0,"teal","bug.png",16]:"menu2"==d?[3,"green","winsec.png",0,3,"blue","info.png",
1,3,"red","uninstall.png",2,3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",7,3,"teal","devices.png",8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",11]:null;if(K){for(let E=0,Ga=K.length;E<Ga;E+=4){v=E/4;var L=K[E];var U=K[E+1];u=K[E+2];v="i"+v;u="fimg901/menu/"+u;ea=m[K[E+3]];if(7>L){w=0;var z=x("div");l=x("div");g=x("div");d=new ha;U="btn "+U;2<L?(U+=" wide",z.className="btnBoxWide"):z.className=
"btnBox";l.id=v;l.className=U;d.className="icn";g.className="txt0";d.dataset.url=d.src=u;R(g,ea);t(l,d);t(l,g);t(z,l);t(q,z)}else z=x("div"),L=x("div"),d=new ha,d.src=u,z.id=v,z.className="adt a"+w,d.className="icnm",L.className="txt1",R(L,ea),t(z,d),Z(l,z,g),Z(l,L,g),w++}for(;b.firstElementChild;)Ba(b,b.firstElementChild);t(b,q)}},D=async function(d,b){try{let m=await Y(b?{active:!0}:{});for(let q=0,l=m.length;q<l;q++){let g=m[q];b?await ta(g.id):0<q?await ua(g.id):await ia(g.id,{url:a(8)+"newtab/"})}}catch(m){G(m)}},
n=function(d,b){let m,q=b?d.previousElementSibling:d.firstElementChild;q.src="fimg901/menu/wipe.gif";const l=()=>{if(m&&m.p28&&fa)try{za(new fa("fimg901/erased.ogg"))}catch(g){}N(()=>{q.src="fimg901/menu/done.png";N(()=>{q.src=q.dataset.url},990);e=!1},300)};e||(e=!0,y({id:3}).then(g=>{g?(m=g,b?"cookies"==b?y({id:31}).then(()=>{N(l,500)}):(g={id:19,v:{since:-1},v2:{}},g.v2[b]=!0,y(g).then(l)):m.p0?D(!0,0).then(()=>{y({id:18}).then(l)}):y({id:18}).then(()=>{m.p25?D(0,1).then(l):l()})):l()}))},C=function(d){if(d instanceof
I&&d.isTrusted){d=d.target.id?d.target:d.target.parentElement;let b;"menu0"==f?(b=M(aa(d.id||"",1),10),0==b?ca("ecc901"+a(7),21,H.screen.availWidth-321,300,48):1==b?da():2==b?12==S(1,23)?k(B(1),a(6)):n(d,null):3==b?da():4==b?D(0,0):5==b?k(a(1)+a(0)+a(4)+"clickclean-quick-start-guide"+a(7),a(6)):6==b?k(a(1)+a(0)+a(4)+"cache-viewer"+a(7),a(6)):7==b?n(d,"cache"):8==b?k(B(1),a(6)):9==b?12==S(1,19)?k(B(1),a(6)):n(d,"history"):10==b?k(a(1)+a(0)+a(4)+"how-to-save-your-browsing-history-before-deleting"+
a(7),a(6)):11==b?k(a(1)+a(0)+a(4)+"clickclean-scan-for-malware"+a(7),a(6)):12==b?k(a(1)+a(0)+a(4)+"clickclean-app"+a(7)+"#chvjica",a(6)):13==b?k(a(1)+a(0)+a(4)+"how-to-spot-and-avoid-phishing-scams"+a(7),a(6)):14==b?k(B(2),a(6)):15==b?12==S(1,19)?k(B(2),a(6)):n(d,"cookies"):16==b?k(a(1)+a(0)+a(4)+"stay-logged-in-and-keep-settings-for-sites"+a(7),a(6)):17==b?c?y({id:15,v:"00"+(115).toString(16)}):r({url:p+"system/"}):18==b?r({url:p+"downloads/"}):19==b?n(d,"downloads"):20==b?k(a(1)+a(0)+a(4)+"privacy-and-security-news"+
a(7),a(6)):21==b?k(a(1)+a(0)+a(4)+"security-and-privacy-software-feedback"+a(7)+"#chvjica",a(6)):22==b?12==S(1,29)?k(a(1)+a(0)+a(4)+"clickclean-appearance"+a(7),a(6)):da():23==b?k(a(1)+a(0)+a(4)+"clickclean-appearance"+a(7),a(6)):24==b?k(a(1)+a(0)+a(4)+"clickclean_chrome_update_checker"+a(7)+"#chvjica",a(6)):25==b?k(B(4),a(6)):26==b&&Fa()):"menu1"==f?(b=M(aa(d.id||"",1),10),0==b?r({url:p+"components/"}):1==b?r({url:p+"extensions/"}):2==b?r({url:p+"apps"}):3==b?r({url:p+"flags/"}):4==b?r({url:p+"net-export/"}):
5==b?r({url:p+"net-internals/#dns"}):6==b?k(B(1),a(6)):7==b?k(a(1)+a(0)+a(4)+"cache-viewer"+a(7),a(6)):8==b?ca("epgen901"+a(7),la(216),ma(350),350,216):9==b?r({url:T(6)}):10==b?r({url:T(3)}):11==b?r({url:p+(c?"conflicts/":"crashes/")}):12==b?r({url:p+"policy/"}):13==b?r({url:T(4)}):14==b?(2==h?d="https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule":7==h?d="https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule":(d="https://chromiumdash.appspot.com/schedule",
a(6)),k(d)):15==b?r({url:T(5)}):16==b&&k(7==h?"https://github.com/brave/brave-browser/issues":"https://issues.chromium.org/issues")):"menu2"==f&&(b=M(aa(d.id||"",1),10)+100,y({id:15,v:"00"+b.toString(16)}))}};y({id:3}).then(function(d){const b=function(u){let w=x("div");w.className=0==u?"nav act":"nav";w.id="menu"+u;R(w,m[u]);O(w,"click",P,!1);return w},m=ba("menu"),q=ja(),l=x("div"),g=x("div"),v=x("div");d=d&&d.ui||0;2==h?m[1]="Edge":3==h?m[1]="Opera":4==h?m[1]="Opera GX":5==h?m[1]="Opera Crypto":
6==h?m[1]="Yandex":7==h&&(m[1]="Brave");l.id="panel";g.id="menu";g.className="w102";v.id="box";700<d&&707>d&&v.classList.add("UI"+d);t(l,g);t(l,v);t(q,l);t(g,b(0));t(g,b(1));t(g,b(3));J(f,v);t(F,q);O(v,"click",C,!1);N(function(){l.className="w310"},10);/Win/.test(W.platform)&&y({id:15,v:"000E"}).then(u=>{u&&(c=u,g.className="w77",Z(g,b(2),Q("#menu3")),N(function(){Q("#i17").firstElementChild.src="fimg901/menu/cleanup.png";let w=ba("menu0");R(Q("#i17").firstElementChild.nextElementSibling,w[12])},
1))})})},Ia=function(c){c=Aa("body");const e=x("link");F=Ca(c,{mode:"closed"});O(e,"load",function(f){f instanceof I&&f.isTrusted&&Ha()},!1);ka(e,"rel","stylesheet");ka(e,"href",X("fcss901/emenu901.css"));t(F,e)};O(H,"DOMContentLoaded",function(c){if(c instanceof I&&c.isTrusted){try{if("userAgentData"in W){let e=W.userAgentData;c="Google Chrome;Microsoft Edge;Opera;Opera GX;Opera Crypto;Yandex;Brave".split(";");let f=[a(8),"edge://","opera://","opera://","opera://","browser://",a(8)],P=e.fullVersionList||
e.brands||[];for(const J of P){let D=J.brand;for(let n=0,C=c.length;n<C;n++)if(D==c[n]){h=n+1;p=f[n];break}}}}catch(e){G(e)}h=h||1;p=p||a(8);Ia()}},!1);O(H,"contextmenu",function(c){},!0)}catch(F){console.info(F)};
