// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2024 Mixesoft. All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
try{const l=function(a){console.info(a)},h=window,e=document,m=e.documentElement,g=l.call,{Event:k,open:t,parseInt:A,chrome:{tabs:{query:E,update:F},windows:{create:G,update:H}}}=h,B=e.createElement.bind(e),I=e.createElementNS.bind(e),J=e.createTextNode.bind(e),K=e.createDocumentFragment.bind(e),L=e.querySelector.bind(e),u=g.bind(m.addEventListener),v=g.bind(m.setAttribute),M=g.bind(m.attachShadow),n=g.bind(m.appendChild),N=g.bind(k.prototype.preventDefault),O=g.bind(k.prototype.stopPropagation),
P=g.bind("".startsWith);g.bind("".indexOf);const C=/Edg/.test(navigator.appVersion||navigator.userAgent||""),w=chrome.runtime.getURL(""),Q=function(a){return A(h.screen.availHeight/2-a/2)},R=function(a){return A(h.screen.availWidth/2-a/2)},S=async function(a,f,b,p,q){try{let c=await E({url:a});c&&0<c.length?(await H(c[0].windowId,{focused:!0}),await F(c[0].id,{active:!0})):await G({type:"popup",url:a,focused:!0,top:f,left:b,width:p,height:q})}catch(c){l(c)}},T=function(a){u(a,"click",function(f){if(f instanceof
k&&f.isTrusted){var b=f.target;b=b&&(b.className||b.parentElement&&b.parentElement.className||"");"a1"===b?S(w+"ecleaner901.html",Q(500),R(770),770,500):"a2"===b?t(C?"https://microsoftedge.microsoft.com/addons/detail/dacknjoogbepndbemlmljdobinliojbk":"https://chromewebstore.google.com/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod"):"a3"===b?t("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvjica"):t(C?"https://www.hotcleaner.com/clickclean-for-microsoft-edge.html":
"https://www.hotcleaner.com/clickclean_chrome.html");O(f);N(f)}},!0)},W=function(){var a=L("body");let f=M(a,{mode:"closed"}),b=[{t:1,l:"div",a:[{n:"class",v:"hst"}],c:[{t:1,l:"h1",c:[{t:3,v:"Thank You for using Click&Clean"}]},{t:1,l:"h3",c:[{t:3,v:"Software Made to Make Your Life Better!"}]},{t:1,l:"button",a:[{n:"class",v:"a0"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg901/opt-home64.webp"}]},{t:1,l:"b",c:[{t:3,v:"Home"}]}]},{t:1,l:"button",a:[{n:"class",v:"a1"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg901/opt-opt64.webp"}]},
{t:1,l:"b",c:[{t:3,v:"Options"}]}]},{t:1,l:"button",a:[{n:"class",v:"a2"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg901/opt-rate64.webp"}]},{t:1,l:"b",c:[{t:3,v:"Rate"}]}]},{t:1,l:"button",a:[{n:"class",v:"a3"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg901/opt-contact64.webp"}]},{t:1,l:"b",c:[{t:3,v:"Support"}]}]},{t:1,l:"br"}]}],p=(c,D)=>{let d,r,x;for(let y=0,U=D.length;y<U;y++)if(d=D[y],1==d.t){r=d.n?I("http://www.w3.org/2000/svg",d.l):B(d.l);for(let z=0,V=d.a&&d.a.length||0;z<V;z++)x=d.a[z],v(r,x.n,x.v);
d.c&&p(r,d.c);n(c,r)}else 3==d.t&&n(c,J(d.v))},q=K();a=B("link");u(a,"load",c=>{c instanceof k&&c.isTrusted&&(p(q,b),n(f,q),T(f))},!1);v(a,"rel","stylesheet");v(a,"href",w+"fcss901/eoptions901.css");n(f,a)},X=function(a){a instanceof k&&a.isTrusted&&W()};P(h.location.href,w)&&u(h,"DOMContentLoaded",X,!0)}catch(l){console.info(l)};
