// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2024 Mixesoft. All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
try{let l;const n=window,d=document,p=d.documentElement,b=Function.prototype.call,{Event:q,Uint8Array:H,Uint32Array:I,parseInt:J,isNaN:K,open:L,resizeTo:M,outerWidth:N,outerHeight:O,innerWidth:P,innerHeight:Q,devicePixelRatio:u,chrome:{runtime:{getURL:B},i18n:{getMessage:R}}}=n,C=d.createElement.bind(d),S=d.createElementNS.bind(d),D=d.createTextNode.bind(d),T=d.createDocumentFragment.bind(d),U=d.querySelector.bind(d),w=b.bind(p.addEventListener),x=b.bind(p.setAttribute),r=b.bind(p.appendChild),V=
b.bind(p.attachShadow),E=n.crypto.getRandomValues.bind(n.crypto),W=b.bind(DocumentFragment.prototype.querySelector),X=b.bind(HTMLInputElement.prototype.select),Y=b.bind(Number.prototype.toString),Z=b.bind(p.focus),aa=b.bind("".split),ba=b.bind("".slice),ca=b.bind("".startsWith),da=b.bind("".toUpperCase),ea=b.bind("".charAt);b.bind(Object.getOwnPropertyDescriptor(Node.prototype,"textContent").set);const fa=function(a){a instanceof q&&a.isTrusted&&L("https://www.hotcleaner.com/tips-for-creating-secure-and-easy-to-remember-passwords.html",
"_blank")},y=function(a){return W(l,a)},ha=function(a,f){let g=new I(25),h;E(g);for(var e=0;e<g.length;e++)h+=Y(g[e],f?16:36);h=ba(h,-a);if(!f){g=new H(1);f="";for(e=0;e<h.length;e++)a=ea(h,e),K(a)&&(E(g),128<g[0]&&(a=da(a))),f+=a;h=f}return h},F=function(){let a=y("#pass"),f=J(y("#length").value,10);a.value=ha(f,0);X(a)},ia=function(a){a instanceof q&&a.isTrusted&&F()},ja=function(a){a instanceof q&&a.isTrusted&&(a=y("#pass"))&&(navigator.clipboard.writeText(a.value),Z(a))},ma=function(){const a=
aa(R("pgen"),";"),f=[{t:1,l:"div",a:[{n:"id",v:"box"}],c:[{t:1,l:"div",a:[{n:"id",v:"hdr"}],c:[{t:1,l:"span",a:[{n:"i18",v:0}]},{t:3,v:" "},{t:1,l:"button",a:[{n:"id",v:"help"},{n:"ec",v:fa}],c:[{t:3,v:"Learn more …"}]}]},{t:1,l:"div",a:[{n:"id",v:"screen"}],c:[{t:1,l:"input",a:[{n:"type",v:"text"},{n:"id",v:"pass"},{n:"spellcheck",v:"false"}]}]},{t:1,l:"div",a:[{n:"id",v:"pan"}],c:[{t:1,l:"label",c:[{t:1,l:"span",a:[{n:"i18",v:1}]},{t:1,l:"input",a:[{n:"type",v:"number"},{n:"id",v:"length"},{n:"value",
v:"12"},{n:"min",v:"5"},{n:"max",v:"99"}]}]}]},{t:1,l:"div",a:[{n:"id",v:"ftr"}],c:[{t:1,l:"button",a:[{n:"i18",v:2},{n:"ec",v:ia},{n:"class",v:"red"},{n:"id",v:"gen"},{n:"title",v:"Generate new password"}]},{t:1,l:"button",a:[{n:"i18",v:3},{n:"ec",v:ja},{n:"class",v:"red"},{n:"id",v:"copy"},{n:"title",v:"Copy new generated password to clipboard"}]}]}]}],g=function(t,G){let m,k,c;for(let z=0,ka=G.length;z<ka;z++)if(c=G[z],1==c.t){m=c.n?S("http://www.w3.org/2000/svg",c.l):C(c.l);for(let A=0,la=c.a&&
c.a.length||0;A<la;A++)k=c.a[A],"ec"===k.n?w(m,"click",k.v,!1):"i18"===k.n?r(m,D(a[k.v])):x(m,k.n,k.v);c.c&&g(m,c.c);r(t,m)}else 3==c.t&&r(t,D(c.v))},h=U("body"),e=T(),v=C("link");l=V(h,{mode:"closed"});w(v,"load",function(t){t instanceof q&&t.isTrusted&&(g(e,f),r(l,e),F())},!1);x(v,"rel","stylesheet");x(v,"href",B("fcss901/epgen901.css"));r(l,v)},na=function(a){a instanceof q&&a.isTrusted&&(M(375*u+(N-P*u),235*u+(O-Q*u)),ma())};ca(n.location.href,B(""))&&w(n,"DOMContentLoaded",na,!0)}catch(l){console.info(l)};
