from pathlib import Path
import os, subprocess

code = (
    "import argparse, csv, hashlib, json, os, subprocess, time\n"
    "from datetime import datetime, timezone\n"
    "from pathlib import Path\n"
    "\n"
    "OLLAMA  = Path(os.environ.get('LOCALAPPDATA','')) / 'Programs' / 'Ollama' / 'ollama.exe'\n"
    "ROOT    = Path('C:/Users/sirok/MoCKA')\n"
    "RAW_DIR = ROOT / 'data' / 'storage' / 'infield' / 'RAW'\n"
    "REDUCED = ROOT / 'data' / 'storage' / 'infield' / 'REDUCED'\n"
    "DONE    = ROOT / 'data' / 'storage' / 'infield' / 'RAW_DONE'\n"
    "EVENTS  = ROOT / 'data' / 'events.csv'\n"
    "MODEL   = 'gemma3:4b'\n"
    "CHUNK   = 3000\n"
    "UTC     = timezone.utc\n"
    "P1 = 'Extract up to 3 key design/structure points as bullet points from the following chat:\\n\\n'\n"
    "P2 = 'Extract up to 3 key risks/problems as bullet points from the following chat:\\n\\n'\n"
    "P3A = 'Step1:\\n'\n"
    "P3B = '\\nStep2:\\n'\n"
    "P3C = '\\nExtract any important insights not covered above. If none, say NO_RESIDUE.\\nText:\\n'\n"
    "\n"
    "REDUCED.mkdir(parents=True, exist_ok=True)\n"
    "DONE.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "def ask(prompt):\n"
    "    r = subprocess.run([str(OLLAMA),'run',MODEL,prompt],\n"
    "        capture_output=True,text=True,encoding='utf-8',timeout=120)\n"
    "    return r.stdout.strip()\n"
    "\n"
    "def chunk_text(text, size=CHUNK):\n"
    "    return [text[i:i+size] for i in range(0, len(text), size)]\n"
    "\n"
    "def get_prev():\n"
    "    rows = list(csv.reader(open(EVENTS, encoding='utf-8-sig'))) if EVENTS.exists() else []\n"
    "    return hashlib.sha256(','.join(rows[-1]).encode()).hexdigest()[:16] if rows else 'GENESIS'\n"
    "\n"
    "def condense_file(fpath):\n"
    "    fpath = Path(fpath)\n"
    "    print('[CONDENSE] ' + fpath.name)\n"
    "    raw = json.load(open(fpath, encoding='utf-8'))\n"
    "    text = raw.get('text', '')\n"
    "    source = raw.get('source', 'unknown')\n"
    "    url = raw.get('url', '')\n"
    "    if not text:\n"
    "        print('[SKIP] no text'); return None\n"
    "    chunks = chunk_text(text)\n"
    "    print('[INFO] ' + str(len(text)) + ' chars / ' + str(len(chunks)) + ' chunks')\n"
    "    all_s1 = []\n"
    "    all_s2 = []\n"
    "    for i, chunk in enumerate(chunks):\n"
    "        print('[Step1-' + str(i+1) + '/' + str(len(chunks)) + ']')\n"
    "        all_s1.append(ask(P1 + chunk))\n"
    "        print('[Step2-' + str(i+1) + '/' + str(len(chunks)) + ']')\n"
    "        all_s2.append(ask(P2 + chunk))\n"
    "    merged_s1 = '\n'.join(all_s1)\n"
    "    merged_s2 = '\n'.join(all_s2)\n"
    "    print('[Step3] residue check...')\n"
    "    s3 = ask(P3A + merged_s1[:2000] + P3B + merged_s2[:2000] + P3C + text[:1000])\n"
    "    ts = datetime.now(UTC).strftime('%Y%m%d_%H%M%S')\n"
    "    eid = 'ERED_' + ts + '_' + source[:4].upper()\n"
    "    h = hashlib.sha256((eid + ts + merged_s1[:100]).encode()).hexdigest()[:16]\n"
    "    result = {'event_id':eid,'source':source,'url':url,'raw_file':fpath.name,\n"
    "              'timestamp':ts,'original_chars':len(text),'chunks':len(chunks),\n"
    "              'step1_structure':merged_s1,'step2_audit':merged_s2,'step3_residue':s3,\n"
    "              'hash':h,'status':'REDUCED'}\n"
    "    out = REDUCED / (ts + '_' + eid + '.json')\n"
    "    json.dump(result, open(out,'w',encoding='utf-8'), ensure_ascii=False, indent=2)\n"
    "    print('[OK] saved: ' + out.name)\n"
    "    prev = get_prev()\n"
    "    with open(EVENTS,'a',encoding='utf-8',newline='') as f:\n"
    "        csv.writer(f).writerow([eid,ts,'condense_worker','condense','chat_condense',\n"
    "            'mocka_condense_worker.py',fpath.name,'worker','internal',\n"
    "            'in_operation','normal','A','infield/REDUCED',\n"
    "            merged_s1[:100],prev,'condense_complete','REDUCED',\n"
    "            'local','condense_pipeline','N/A','N/A',\n"
    "            'hash='+h+'|source='+source+'|chunks='+str(len(chunks))+'|chars='+str(len(text))])\n"
    "    fpath.rename(DONE / fpath.name)\n"
    "    print('[OK] moved to RAW_DONE')\n"
    "    return out\n"
    "\n"
    "def get_unprocessed():\n"
    "    done_names = {f.name for f in DONE.glob('*.json')}\n"
    "    reduced_raws = set()\n"
    "    for r in REDUCED.glob('*.json'):\n"
    "        try:\n"
    "            d = json.load(open(r, encoding='utf-8'))\n"
    "            reduced_raws.add(d.get('raw_file',''))\n"
    "        except: pass\n"
    "    return [f for f in sorted(RAW_DIR.glob('*.json'), key=lambda x: x.stat().st_mtime)\n"
    "            if f.name not in done_names and f.name not in reduced_raws]\n"
    "\n"
    "def main():\n"
    "    parser = argparse.ArgumentParser()\n"
    "    parser.add_argument('--once', action='store_true')\n"
    "    parser.add_argument('--file')\n"
    "    args = parser.parse_args()\n"
    "    if args.file:\n"
    "        condense_file(args.file); return\n"
    "    if args.once:\n"
    "        files = get_unprocessed()\n"
    "        if not files: print('[INFO] no unprocessed files'); return\n"
    "        for f in files: condense_file(f)\n"
    "        print('[DONE] ' + str(len(files)) + ' files processed'); return\n"
    "    print('[WORKER] watching... Ctrl+C to stop')\n"
    "    while True:\n"
    "        files = get_unprocessed()\n"
    "        if files:\n"
    "            for f in files: condense_file(f)\n"
    "        else:\n"
    "            print('[WORKER] waiting... ' + datetime.now(UTC).strftime('%H:%M:%S'))\n"
    "        time.sleep(60)\n"
    "\n"
    "if __name__ == '__main__':\n"
    "    main()\n"
)

compile(code, 'test', 'exec')
print('syntax OK')

dst = Path(r'C:\Users\sirok\MoCKA\scripts\mocka_condense_worker.py')
dst.write_text(code, encoding='utf-8')
print('[OK] ' + str(dst.stat().st_size) + ' bytes')
print(dst.read_text(encoding='utf-8')[:30])

import subprocess
subprocess.run(['git','add','scripts/mocka_condense_worker.py'], cwd=r'C:\Users\sirok\MoCKA')
subprocess.run(['git','commit','-m','fix: condense worker 構文修正完了'], cwd=r'C:\Users\sirok\MoCKA')
subprocess.run(['git','push','origin','main'], cwd=r'C:\Users\sirok\MoCKA')
