// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2024 Mixesoft. All Rights Reserved.
// Minified by Google Closure Compiler 20240317
'use strict';
try{let d,za,J,ba=!1,la,Aa;const k=function(a){console.info(a)},pb=function(){},ca=self,r=[],l=k.call,{navigator:S,Object:qb,URL:ma,Date:na,parseInt:z,isNaN:rb,setTimeout:K,decodeURIComponent:sb,encodeURIComponent:tb,JSON:{stringify:Ba,parse:Ca},Math:{random:T,floor:ub},chrome:{runtime:oa,runtime:{setUninstallURL:vb,onMessage:pa,onStartup:wb,onInstalled:xb},tabs:{create:C,remove:qa,update:ra,query:D,move:yb,onUpdated:L,onRemoved:sa},windows:{getAll:Da,create:da,update:zb,getLastFocused:Ab,onRemoved:Ea},
action:{setTitle:Bb,setBadgeBackgroundColor:Cb,setBadgeText:Db,setBadgeTextColor:Fa},browsingData:{remove:M,removeServiceWorkers:Eb},history:{deleteUrl:ta,search:U,getVisits:Fb,deleteRange:Gb,onVisited:ea,onVisitRemoved:V},cookies:{get:Hb,set:Ib,getAll:Ga,remove:Jb},i18n:{getMessage:Ha},contextMenus:{create:E,removeAll:Kb,onClicked:Lb},storage:{local:N},scripting:{executeScript:Mb},management:{getSelf:Nb}}}=ca,p=l.bind(pa.addListener),t=l.bind(pa.removeListener),Ia=N.set.bind(N),Ob=N.get.bind(N);
N.clear.bind(N);const Pb=oa.id,O=l.bind(Number.prototype.toString),ua=l.bind("".charCodeAt),fa=l.bind("".charAt),F=l.bind("".startsWith),u=l.bind("".slice),ha=l.bind("".split),va=l.bind("".indexOf),Qb=l.bind("".match),P=l.bind("".replace),Rb=l.bind("".toLowerCase),v=l.bind(r.push),Ja=l.bind(r.join),Ka=l.bind(r.splice),w=l.bind(r.indexOf),Sb=l.bind(r.map),La=l.bind(r.forEach),Ma=l.bind(r.filter),Tb=l.bind(r.includes);l.bind(na.prototype.getDay);const Ub=ca.fetch.bind(ca),Na=String.fromCharCode,A=na.now,
Vb=".com hotcleaner google microsoft clients2 ghgabhipcejejjmhhchfonmamedcbeod .net update2 service https:// doubleclick api64 accounts login live .html clickclean".split(" "),g=function(a){return Vb[a]},W=oa.getURL(""),G=A(),Wb=/Win/.test(S.platform),q=g(9)+"www."+g(1)+g(0)+"/",Oa=g(9)+"chromewebstore."+g(2)+g(0)+"/detail/"+g(5),X=function(a,b){return ub(T()*(b+1-a))+a},Pa=function(){let a=O(4294967296*T()>>>0,16),b=O((4294967296*T()&4294922239|16384)>>>0,16),c=O((4294967296*T()&3221225471|2147483648)>>>
0,16),e=O(4294967296*T()>>>0,16);8>a.length&&(a=u("0000000"+a,-8));8>b.length&&(b=u("0000000"+b,-8));8>c.length&&(c=u("0000000"+c,-8));8>e.length&&(e=u("0000000"+e,-8));return Ja([a,u(b,0,4),u(b,4),u(c,0,4),u(c,4)+e],"-")},Qa=function(a){let b=0,c,e,f=a.length;for(e=0;e<f;e++)c=ua(a,e),b=(b<<5)-b+c,b|=0;return b},Xb=async function(){let a=f=>{let h=[0,0,0,0];f="string"==typeof f&&ha(f,".")||[];let m;for(let n=0,Q=f.length;n<Q;n++)m=z(f[n]),isNaN(m)||(h[n]=m);return h};if("userAgentData"in S){let f=
S.userAgentData;f.getHighEntropyValues&&(f=await f.getHighEntropyValues(["fullVersionList"]));let h,m;var b=0;let n="Google Chrome;Microsoft Edge;Opera;Opera GX;Opera Crypto;Yandex;Brave".split(";"),Q=n.length;var c=f.fullVersionList||f.brands||[];for(var e of c){c=e.brand;for(let x=0;x<Q;x++)if(c==n[x]){b=x+1;m=e.version;d.bn=n[x];break}"Chromium"==c&&(h=e.version)}e=Rb(fa(f.platform||"",0));b=[b,a(m),"w"==e?1:"m"==e?2:"c"==e?3:"l"==e?4:0,a(h)]}return b||[0,[0,0,0,0],"",[0,0,0,0]]},H=async function(a,
b,c){let e=null,f=2;try{let h=await Ub(a,b);h&&(h.ok?(e=await h[c](),f=0):"opaqueredirect"==h.type&&(f=1))}catch(h){k(a+" "+h)}return[e,f]},Ra=function(a){if(3>a){const b=g(9)+g(4)+"."+g(2)+g(0)+"/"+g(8)+"/"+g(7)+"/crx?x=id%3D"+g(5)+"%26v%3D9.8.2.0%26uc";H(b,{method:"GET",cache:"no-store",credentials:"include",redirect:"manual"},"text").then(c=>{[,c]=c;1<c&&K(Ra,3300,a+1)})}},Yb=async function(){let a=!1;try{let b=(await Nb())?.hostPermissions??[];a=Tb(b,"https://*/*")}catch(b){k(b)}return a},Zb=
async function(){let a;try{let b=await Ab();if(b&&"normal"==b.type)a=b;else{b=await Da();for(let c=0,e=b.length;c<e;c++)if("normal"==b[c].type){a=b[c];break}}}catch(b){k(b)}return a},Sa=async function(a){try{await zb(a.windowId,{focused:!0}),await ra(a.id,{active:!0})}catch(b){k(b)}return a},$b=async function(a){let b;try{let c={url:a.q||a.u};a.t&&(c.title=a.t);let e=await D(c);e&&0<e.length?(b=e[0],await Sa(b)):b=await C({url:a.u,active:!0})}catch(c){k(c)}return b},ac=async function(a){let b;try{let c=
{url:a.q||a.u};a.t&&(c.title=a.t);let e=await D(c);if(e&&0<e.length)b=e[0];else{let f=await Zb(),h=f?f.id:null,m=await da({url:a.u,type:"normal",state:h?"minimized":"maximized"});e=await D({windowId:m.id});b=e[0];h&&(b=await yb(b.id,{index:-1,windowId:h}))}await Sa(b)}catch(c){k(c)}return b},y=function(a){"b"==fa(a.u,0)?C({url:a.u}):Wb?ac(a):$b(a)},Ta=function(a,b){for(let c=0,e=b.length;c<e;c++)0>w(a,b[c])&&v(a,b[c])},Ua=function(a,b){for(let c=0,e=b.length;c<e;c++)-1<w(a,b[c])&&Ka(a,c,1)},cc=async function(a){"sf"in
a&&("gg"in a&&(d.gg=a.gg),"gf"in a&&(d.gf=a.gf),"goc"in a&&(d.go.length=0),"gpc"in a&&(d.gp.length=0),"gor"in a&&Ua(d.go,a.gor),"gpr"in a&&Ua(d.gp,a.gpr),"goa"in a&&Ta(d.go,a.goa),"gpa"in a&&Ta(d.gp,a.gpa));"dc"in a&&(d.dc=a.dc);"sm"in a&&("mr"in a&&(d.mr=a.mr),"ma"in a&&(d.ma=a.ma),"ml"in a&&(d.ml=a.ml),"mt"in a&&d.mt!=a.mt&&(d.mt&&t(sa,wa),d.mt=a.mt,d.mt&&p(sa,wa)));"rtc"in a&&await M({origins:[g(9)+g(10)+g(6)]},{cookies:!0,cache:!0,localStorage:!0});"op"in a&&await bc(a.op);await I()},Xa=async function(a){let b;
try{const [c,e,f,h]=await Xb(),m=await U({text:"",maxResults:1E3,startTime:1}),n=A(),Q=m&&m.length||0,x=z((n-(d.ai||0))/6E4),B=z((n-(d.md||0))/6E4),R={a:1,b:9820,c:x,d:d.au,e:f,f:c,g:e[0],h:e[1],i:e[2],j:e[3],k:h[0],l:h[1],m:h[2],n:h[3],o:(new na).getTimezoneOffset()/60,p:S.language||"",q:Q,r:d.mc||0,s:B,t:d.ma||0,u:d.p33||0,v:d.mr,w:d.mt||0,x:d.dc||0,y:d.ms||0,z:d.ml||0};if(a)for(let Va in a)R[Va]=a[Va];let [ia,Wa]=await H(g(9)+g(11)+g(0)+"/upd2",{method:"POST",cache:"no-store",body:Ba(R),headers:{"Content-Type":"application/json"}},
"json");0==Wa&&await cc(ia);b=Wa||ia}catch(c){k(c),b=5}return b},dc=function(){var a=G-16066872E5;a=108E5>a?0:z(a/108E5,10);d.uf!=a&&(d.uf=a,Xa(null))},ja=function(){return{ver:"",wl:["c.com",0,"google.com",0],timeType:10,time:0,dev:0,ui:700,gg:1,gf:0,go:[],gp:[],uf:0,bn:"",mc:0,md:0,mr:0,mt:0,ms:0,ma:0,ml:0,uid:"",dc:12,ai:0,au:0,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:0,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,
p30:0,p31:1,p32:1,p33:1}},ec=function(a){a=Qb(a,/.{1,2}/g);let b=[3,0,0,-3],c,e="";for(let f=0,h=a.length;f<h;f++)c=b[f%4],e=f+c<h?e+Na(z(a[f+c],16)):e+Na(z(a[f],16));return e},fc=function(a){let b="",c=[3,0,0,-3],e;for(let f=0,h=a.length;f<h;f++)e=c[f%4],b=f+e<h?b+O(ua(a,f+e),16):b+O(ua(a,f),16);return b},gc=function(a){return fc(Ba(a))},hc=function(a){let b;try{"{"!=fa(a,0)&&(a=ec(a)),b=Ca(a)}catch(c){b=void 0}return b.constructor===qb?b:void 0},ic=function(a){const b=ja();for(let c in a)c in b?
typeof a[c]!==typeof b[c]&&(a[c]=b[c]):delete a[c];for(let c in b)c in a||(a[c]=b[c]);return a},Ya=function(a){J=G-1E3;Ia({s:J}).then(a).catch(a)},I=async function(){let a;try{if(d){d.ver="9.8.2.0";3E3<d.wl.length&&(d.wl.length=3E3);let b=gc(d);await Ia({ops:b})}}catch(b){k(b),a=b}return a},kc=function(a){if(d&&a){for(var b of"gg gf go gp uf bn mc md mr ms mt ma ml uid dc ai au".split(" "))delete a[b];d.p26!==a.p26&&Za(a.p26);d.p29!==a.p29?$a(a.p29):d.p30!==a.p30?ab(a.p30):d.p31!==a.p31?(a.p31&&jc(),
bb(a.p31)):d.p32!==a.p32&&(a.p32?(p(ea,Y),Z()):(t(ea,Y),t(V,aa)));b=ja();for(let c in a)c in b&&typeof a[c]==typeof b[c]&&(d[c]=a[c]);I()}},lc=function(){let a=ja();a.ver="9.8.2.0";a.ai=G;a.uid=Pa();J=G-1E3;return a},xa=function(){d?(y({u:q}),K(function(){y({u:q+g(16)+"/install-"+g(16)+g(15)})},2500)):K(xa,1E3)},mc=function(){try{let a=d.wl||[],b=w(a,g(1)+g(0));-1<b&&Ka(a,b,2)}catch(a){k(a)}},cb=function(a){d?(d.au=z(Ja(ha(a||"9.8.1.0","."),"")),d.ai=d.ai||G,d.uid=d.uid||Pa(),mc(),I()):K(cb,1E3,a)},
db=function(a){la==a?la=-9:d&&d.p26&&Da({}).then(b=>{b&&0==b.length&&da({type:"popup",url:"ecc901"+g(15),focused:!0,top:21,left:21,width:300,height:48}).catch(c=>{ya(ka()).then(()=>{k("cbd")})})})},Za=function(a){a?p(Ea,db):t(Ea,db)},eb=function(a,b,c){F(c.url||"","chrome://history")&&"complete"==b.status&&ra(a,{url:"chrome://newtab"}).catch(k)},ab=function(a){a?p(L,eb):t(L,eb)},fb=function(a,b){a&&F(a,"http")&&0==F(a,q)&&Mb({target:{tabId:b},files:["fjs901/ebtn901.js"]}).catch(k)},jc=async function(){try{let a=
await D({status:"complete",windowType:"normal",url:["http://*/*","https://*/*"]});for(let b,c=0,e=a.length;c<e;c++)b=a[c],-1<b.id&&fb(b.url,b.id)}catch(a){k(a)}},gb=function(a,b,c){c&&-1<a&&"complete"===b.status&&fb(c.url,a)},bb=function(a){a?p(L,gb):t(L,gb)},hb=function(a){try{0<a&&(Fa&&Fa({color:"#fff"}),Cb({color:[99<a?233:21,21,21,255]})),Db({text:0<a?99<a?"99+":a+"":""}),Bb({title:0<a?"History records: "+a+"\nClick&Clean":"\nClick&Clean"})}catch(b){k(b)}},nc=async function(a,b){try{0>a.since&&
(a.since=ka()),"cache"in b&&(b.cacheStorage=!0),await M(a,b)}catch(c){k(c)}return d?.p28},ya=async function(a){try{let b={history:!!d.p1,downloads:!!d.p2,cache:!!d.p3,cacheStorage:!!d.p3,passwords:!!d.p5,formData:!!d.p6,localStorage:!!d.p7,webSQL:!!d.p8,indexedDB:!!d.p9,fileSystems:!!d.p10,appcache:!!d.p11};Eb&&(b.serviceWorkers=!!d.p12);await M({since:a},b);d.dev&&(await M({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{cookies:!!d.p13,localStorage:!!d.p14,webSQL:!!d.p15,
indexedDB:!!d.p16,fileSystems:!!d.p17,cacheStorage:!!d.p18,appcache:!!d.p18}),await M({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{cookies:!!d.p19,localStorage:!!d.p20,webSQL:!!d.p21,indexedDB:!!d.p22,fileSystems:!!d.p23,cacheStorage:!!d.p24,appcache:!!d.p24}));d.p4&&await ib(null)}catch(b){k(b)}},oc=async function(){let a=[];try{let b=await Ga({});for(let c=0,e=b.length;c<e;c++)v(a,b[c].domain)}catch(b){k(b)}return[a,d?.wl]},pc=function(){var a=d.dc||12;const b=[g(12)+
"."+g(2)+g(0),g(2)+g(0)];0==a||10==a?v(b,g(10)+g(6)):2==a||12==a?v(b,"youtube"+g(0)):(3==a||13==a)&&v(b,"youtube"+g(0),g(10)+g(6));if(9<a){let c=g(2);a=ha("com.au|be|ca|ch|cn|de|dk|ee|es|fi|fr|gr|ie|co.il|it|co.jp|co.kr|lt|lv|nl|no|co.nz|pl|pt|ru|se|com.tw|co.uk","|");La(a,e=>{v(b,c+"."+e)})}return b},qc=function(){const a=d.wl||ja().wl,b=w(a,g(2)+g(0)),c=-1<b?pc():[];-1<w(a,g(14)+g(0))&&v(c,g(13)+"."+g(14)+g(0));for(let e=0,f=a.length;e<f;e+=2)e!=b&&v(c,a[e]);return[c,-1<w(a,"c.com")]},rc=function(a,
b){let c;"SOCS"!=b||"google.com"!=a&&"youtube.com"!=a?"CSTD"==b||"FCCDCF"==b||"FCNEC"==b?c=!0:"BCP"==b&&"bing.com"==a?c=!0:"datr"==b&&"facebook.com"==a?c=!0:"GUC"==b&&"yahoo.com"==a?c=!0:"d_prefs"==b&&"x.com"==a?c=!0:"discord.com"==a&&"OptanonAlertBoxClosed"==b?c=!0:"ig_did"==b&&"instagram.com"==a?c=!0:"eu_cookie"==b&&"www.reddit.com"==a&&(c=!0):c=!0;return c},ib=async function(a){try{let b=await Ga({}),[c,e]=qc();La(b,f=>{"."==fa(f.domain,0)&&(f.domain=u(f.domain,1))});a&&(b=Ma(b,f=>-1<w(a,f.domain)));
b=Ma(b,f=>-1<w(c,f.domain)?!1:e&&rc(f.domain,f.name)?!1:!0);for(let f=0,h=b.length;f<h;f++){let m=b[f];await Jb({url:"http"+(m.secure?"s":"")+"://"+m.domain+m.path,name:m.name})}}catch(b){k(b)}},bc=async function(a){try{const b=g(10)+g(6),c="https://"+b+"/";await Hb({name:"id",url:c})||Ib({url:c,domain:b,name:"id",value:"OPT_OUT",secure:!0,sameSite:"no_restriction",expirationDate:z(A()/1E3)+a})}catch(b){k(b)}},ka=function(){let a=d.timeType;return 10==a?1:0==a?J:9==a?d.time:A()-36E5*[0,1,2,4,8,10,
12,24,168][a]},sc=function(a){return new Promise((b,c)=>{if(32==a.length){let e,f=function(h,m,n){h==e&&"complete"==n.status&&(t(L,f),qa(e).then(()=>{b("favIconUrl"in n)}).catch(b))};C({url:"chrome-extension://"+a+"/manifest.json",active:!1,pinned:!0}).then(h=>{e=h.id;p(L,f)}).catch(b)}else b()})},Y=function(){U({text:"",maxResults:100,startTime:1}).then(a=>{hb(a&&a.length||0)}).catch(k)},aa=function(a){a.allHistory?hb(0):Y()},Z=function(){p(V,aa);Y()},jb=async function(a,b){if(a){({origin:a}=new ma(a));
let c;if(1<b){c=await D({url:a+"/*"});await C({url:"about:blank"});for(let e=0,f=c.length;e<f;e++)await qa(c[e].id)}await M({origins:[a]},{cookies:3==b,cache:!0,cacheStorage:!0,localStorage:!0,indexedDB:!0,fileSystems:!0});if(1<b){d.p32&&t(V,aa);a+="/";c=await U({text:"",startTime:0,endTime:A(),maxResults:99999});for(let e=0,f=c.length;e<f;e++)F(c[e].url,a)&&await ta({url:c[e].url});d.p32&&Z();await ra({url:"chrome://newtab"})}}},tc=async function(a){try{let b=a.length;if(0<b){d.p32&&t(V,aa);for(let c=
0,e=b;c<e;c+=2)await Gb({startTime:a[c],endTime:a[c+1]});d.p32&&Z()}}catch(b){k(b)}},uc=async function(a){try{d.p32&&t(V,aa);for(let b=0,c=a.length;b<c;b++)await ta({url:a[b]});d.p32&&Z()}catch(b){k(b)}},vc=async function(a){let b=[],c=a?.startTime||0,e=a?.endTime||A(),f=await U({text:"",startTime:c,endTime:e,maxResults:a?.maxResults||99999});await Promise.allSettled(Sb(f,(h,m)=>new Promise((n,Q)=>{Fb({url:h.url}).then(x=>{for(let B,R=0,ia=x.length;R<ia;R++)B=x[R],B.visitTime>c&&B.visitTime<e&&v(b,
{i:m,url:h.url,time:B.visitTime,label:h.title||h.url,transition:B.transition,isLocal:B?.isLocal||!0});f[m]=h.url;n()})})));return{visits:b,urls:f}},kb=function(a,b,c){if(b?.id===Pb){try{a=Ca(a)}catch(f){a={id:404}}let e=a.id;0===e?(la=a.v,c(d.p28)):1===e?(d.ver="9.8.2.0",c({v:d,u:b.tab.url,t:J})):2===e?c(b.tab.url):3===e?(d.ver="9.8.2.0",c(d)):7===e?(kc(a.v),c()):9===e?(y(a.v),c()):10===e?uc(a.v).then(c):11===e?tc(a.v).then(c):12===e?vc(a.v).then(c):15===e?H("http://localhost:27077/mc/"+a.v,{method:"POST",
cache:"no-store",body:a.v2?a.v2:null,credentials:"omit"},"text").then(f=>{[f]=f;c(f)}):18===e?ya(ka()).then(c):19===e?nc(a.v,a.v2).then(c):30===e?oc().then(c):31===e?ib(a.v).then(c):34===e?c(d.wl):35===e?(a=a.v,a instanceof Array&&(3E3<a.length&&(a.length=3E3),d.wl=a,I()),c()):40===e?jb(b?.tab?.url,a.v).then(c):54===e?wc(a.v).then(c):102===e?(b=a?.v?.u??"",(F(b,q)||F(b,"chrome"))&&y(a.v),c()):103===e?da({url:a.u,state:"maximized",incognito:!0}).then(c):130===e?sc(a.v).then(c):700===e?(a=a.v,0==rb(a)&&
699<a&&712>a?(d.ui=a,I().then(c)):c()):c()}},xc=function(a,b){if("object"==typeof a&&"string"==typeof a.menuItemId){var c=a.menuItemId;"9824"===c?y({u:q+"support-click-and-clean-development"+g(15)}):"9825"===c?y({u:Oa+"/reviews"}):"9826"===c?y({u:q+"privacy-and-security-news"+g(15)}):"9827"===c?y({u:q+"security-and-privacy-software-feedback"+g(15)+"#chvjica"}):"9833"===c&&"object"==typeof b&&"string"==typeof b.url?jb(b?.url,3):"9834"===c?(a=a.linkUrl||"",b=va(a,"&url="),0<b&&(c=va(a,"&",b+5),a=sb(u(a,
b+5,c))),y({u:a})):"9835"===c&&y({u:g(9)+"encrypted."+g(2)+g(0)+"/search?q="+tb(a.selectionText)+"&tbo=1"})}},$a=function(a){Kb().then(()=>{let b=()=>{let c=oa.lastError;c&&k(c)};E({id:"9824",title:"$ Contribute …",contexts:["action"]},b);E({id:"9825",title:"♥ Rate …",contexts:["action"]},b);E({id:"9826",title:"♫ What's New …",contexts:["action"]},b);E({id:"9827",title:"Feedback …",contexts:["action"]},b);if(a){let c=ha(Ha("ctxMenu"),";");E({id:"9833",title:c[0],contexts:["page"]},b);E({id:"9834",
title:c[1],contexts:["link"]},b);E({id:"9835",title:c[2],contexts:["selection"]},b)}})},yc=async function(a){try{let b={method:"GET",cache:"no-store"},[c]=await H(a.n,b,"text"),[e]=await H(W+"fjs901/"+a.j,b,"text"),[f]=await H(W+"fcss901/"+a.c,b,"text");if(c&&e&&f){let h=0<va(c,"<template")?"</template>":"</head>";c=P(c,"sheet","");c=P(c,"src","url");e=P(e,"ARGS","["+d.ma+","+d.ms+"]");a.v&&(e=P(e,"I18N",a.v));c=P(c,h,"<style>"+f+"</style><script>"+e+"\x3c/script>"+h);a.n="data:text/html;charset=utf-8,"+
encodeURIComponent(c)}}catch(b){k(b)}return a},zc=async function(a){try{let b={url:a.n};if(0==d.ma)return b.active=!0,await C(b);10==d.ma?(b.type="normal",b.state="maximized"):(b.type="panel",b.top=X(8,133),b.left=X(8,133),b.width=a.w+X(1,34),b.height=a.h+X(1,34));9<d.ma&&(b.incognito=!0);return await da(b)}catch(b){k(b)}},lb=async function(){try{let a=d.ms=d.mt;d.mt=0;d.md=A();d.mc++;1==a&&(d.au=0);if(!await I()){1==d.ml&&9<d.ma&&(d.ml=0);let b;if(1==a)b={w:800,h:600},2==d.ml?b.n=q+"clickclean-updated"+
g(15):(b.n=W+"eupdated901.html",0==d.ml&&(b.c="eupdated901.css"));else if(2==a)b={w:620,h:410},2==d.ml?b.n=q+"download-new-clickclean-version"+g(15):(b.n=W+"eversion901.html",0==d.ml&&(b.c="eversion901.css"));else if(2<a)if(b={w:510,h:233},2==d.ml)b.n=q+"security-checkup-"+(3==a?"browsing-history":"browser-version")+g(15);else if(b.n=W+"ecue901.html",0==d.ml){let c=Ha("msg"+a);4==a&&d.bn&&(c=P(c,"Chrome",d.bn+"™"));b.c="ecue901.css";b.v=c}b&&(0==d.ml?(b.j="ecue901.js",b=await yc(b)):
1==d.ml&&(b.n+="#"+A()+"-"+d.ma+"-"+a),await zc(b))}}catch(a){k(a)}},wa=function(a,b){b&&0==b.isWindowClosing&&U({text:"",maxResults:d.mr||35,startTime:1}).then(c=>{c=c&&c.length||0;let e=d.mr||X(21,34);c>=e&&lb()})},mb=function(a,b){C({url:"eblocked901"+g(15)})},nb=function(a){D({url:a+"*"},function(b){let c=b.length;if(0<c){C({url:"chrome://newtab"});for(let e=0;e<c;e++)qa(b[e].id),ta({url:b[e].url})}})},ob=function(a){try{const b=new ma(a),c=b.origin;-1<w(d.go,Qa(c))?nb(c+"/"):-1<w(d.gp,Qa(c+
b.pathname))&&nb(c+b.pathname)}catch(b){k(b)}},Ac=function(a,b,c){if(ba&&(b||S.onLine)){let e;c?(b=q,e={origin:b}):(e=new ma(a),b=e.origin+e.pathname);D({url:b+"*"}).then(f=>{ba=!1;1>f.length&&mb(a,e.origin)})}},Bc=function(a){a=a.url;"string"==typeof a&&(d.gg?0==ba&&F(a,q)?(ba=!0,K(Ac,900,a,!1,!0)):d.gf&&ob(a):d.gf&&ob(a))},wc=async function(a){let b;if(a){const c=a.c;if(89==c)[a]=await H(g(9)+g(11)+g(0)+"/dbge",{method:"POST",cache:"no-store",body:a.p},"text"),"ok"==a&&(b=Aa=200);else if(Aa){let e=
a.o||{};for(let f in e)d[f]=e[f];10==c?b=await Xa(a.p):30==c?b=await I():1==c?await lb():51==c?xa():52==c&&mb(Oa,null)}else b=403}return b};p(pa,(a,b,c)=>{d?kb(a,b,c):v(r,[a,b,c]);return!0});p(wb,()=>{za=!0});p(xb,a=>{const b="object"==typeof a&&a.reason||"";"install"===b?xa():"update"===b&&"9.8.2.0"!==a.previousVersion&&cb(a.previousVersion||"9.8.1.0")});vb(q+"security-and-privacy-software-feedback"+g(15)+"#chujica");(async function(){let a;try{let {ops:b,s:c}=await Ob(["ops","s"]);J=c||G-1E3;if("string"==
typeof b){let e=hc(b);"object"==typeof e&&(a=ic(e))}}catch(b){k(b)}return a||lc()})().then(a=>{d=a;for(let b=0,c=r.length;b<c;b++)kb.apply(ca,r[b]);if(za)if($a(d.p29),d.p26){let b=ka();Ya(()=>{ya(b)})}else Ya(pb);d.p26&&Za(!0);d.p30&&ab(!0);d.p31&&bb(!0);d.p32&&(p(ea,Y),Z());d.gf=1;d.gg=1;(d.gg||d.gf)&&p(ea,Bc);p(Lb,xc);181257474E4>G&&K(dc,3E3);d.mt&&p(sa,wa);Yb().then(b=>{b&&Ra(0)})})}catch(d){console.info(d)};
